import { type Theme } from '@rainbow-me/rainbowkit';

export const operonRainbowTheme: Theme = {
  blurs: {
    modalOverlay: 'blur(8px)',
  },
  colors: {
    accentColor: '#22C55E',
    accentColorForeground: '#FFFFFF',
    actionButtonBorder: '#1F2B3D',
    actionButtonBorderMobile: '#1F2B3D',
    actionButtonSecondaryBackground: '#111827',
    closeButton: '#9CA3AF',
    closeButtonBackground: '#1F2B3D',
    connectButtonBackground: '#22C55E',
    connectButtonBackgroundError: '#EF4444',
    connectButtonInnerBackground: '#111827',
    connectButtonText: '#FFFFFF',
    connectButtonTextError: '#FFFFFF',
    connectionIndicator: '#22C55E',
    downloadBottomCardBackground: '#0A0E14',
    downloadTopCardBackground: '#111827',
    error: '#EF4444',
    generalBorder: '#1F2B3D',
    generalBorderDim: '#151D2B',
    menuItemBackground: '#111827',
    modalBackdrop: 'rgba(0, 0, 0, 0.6)',
    modalBackground: '#0A0E14',
    modalBorder: '#1F2B3D',
    modalText: '#F9FAFB',
    modalTextDim: '#9CA3AF',
    modalTextSecondary: '#D1D5DB',
    profileAction: '#111827',
    profileActionHover: '#1F2B3D',
    profileForeground: '#0A0E14',
    selectedOptionBorder: '#22C55E',
    standby: '#F59E0B',
  },
  fonts: {
    body: 'Inter, system-ui, sans-serif',
  },
  radii: {
    actionButton: '8px',
    connectButton: '8px',
    menuButton: '8px',
    modal: '16px',
    modalMobile: '16px',
  },
  shadows: {
    connectButton: '0 4px 12px rgba(34, 197, 94, 0.15)',
    dialog: '0 8px 32px rgba(0, 0, 0, 0.4)',
    profileDetailsAction: '0 2px 6px rgba(0, 0, 0, 0.2)',
    selectedOption: '0 0 0 2px #22C55E',
    selectedWallet: '0 0 0 2px #22C55E',
    walletLogo: '0 2px 8px rgba(0, 0, 0, 0.2)',
  },
};
