// Shared nonce verification logic
// Used by both /api/auth/nonce (generation) and /api/auth/wallet (verification)

let redisClient: any = null;
const memStore = new Map<string, number>();

async function getRedis() {
  if (redisClient) return redisClient;
  if (process.env.UPSTASH_REDIS_REST_URL && process.env.UPSTASH_REDIS_REST_TOKEN) {
    const { Redis } = await import('@upstash/redis');
    redisClient = Redis.fromEnv();
    return redisClient;
  }
  return null;
}

/**
 * In production, Redis is required for nonce storage. The in-memory Map
 * does not work across Vercel serverless instances — a nonce generated by
 * one instance is invisible to another, causing random auth failures.
 * Mirrors the fail-closed pattern in lib/rate-limit.ts.
 */
function requireRedisInProd(): void {
  if (process.env.NODE_ENV === 'production') {
    throw new Error('Nonce store requires Redis in production — set UPSTASH_REDIS_REST_URL and UPSTASH_REDIS_REST_TOKEN');
  }
}

export async function generateNonce(): Promise<string> {
  const nonce = crypto.randomUUID();
  const redis = await getRedis();

  if (redis) {
    await redis.set(`nonce:${nonce}`, '1', { ex: 300 });
  } else {
    requireRedisInProd();
    const now = Date.now();
    for (const [key, expiresAt] of memStore) {
      if (expiresAt < now) memStore.delete(key);
    }
    if (memStore.size >= 10000) throw new Error('Nonce store full');
    memStore.set(nonce, now + 5 * 60 * 1000);
  }

  return nonce;
}

export async function verifyNonce(nonce: string): Promise<boolean> {
  if (!nonce) return false;
  const redis = await getRedis();

  if (redis) {
    // Atomic delete-and-check: single Redis command, no TOCTOU race.
    // Returns number of keys removed (0 = nonce didn't exist or already used).
    const deleted = await redis.del(`nonce:${nonce}`);
    return deleted > 0;
  }

  requireRedisInProd();
  const expiresAt = memStore.get(nonce);
  if (!expiresAt || expiresAt < Date.now()) return false;
  memStore.delete(nonce);
  return true;
}
