import { type Language } from '@/types/api';

// ─── English ──────────────────────────────────────────────────────────────

const en = {
  'nav.home': 'Dashboard', 'nav.nodes': 'AI Agents', 'nav.sale': 'Node Sale', 'nav.referrals': 'Referrals', 'nav.settings': 'Settings', 'nav.docs': 'Documentation', 'nav.support': 'Support',
  'btn.connect_wallet': 'Connect Wallet', 'btn.disconnect': 'Disconnect', 'btn.buy_now': 'Buy Now', 'btn.approve': 'Approve', 'btn.confirm': 'Confirm', 'btn.cancel': 'Cancel', 'btn.copy': 'Copy', 'btn.copied': 'Copied!', 'btn.view_all': 'View All', 'btn.load_more': 'Load More', 'btn.retry': 'Retry', 'btn.claim': 'Claim', 'btn.delegate': 'Delegate', 'btn.share': 'Share',
  'page.home.title': 'Dashboard Overview', 'page.nodes.title': 'My AI Agents', 'page.sale.title': 'Node Sale', 'page.referrals.title': 'Referral Network', 'page.settings.title': 'Settings',
  'stats.total_nodes': 'Total Nodes', 'stats.active_nodes': 'Active Nodes', 'stats.total_earnings': 'Total Earnings', 'stats.pending_commissions': 'Pending Commissions', 'stats.network_size': 'Network Size', 'stats.partner_tier': 'Partner Tier', 'stats.nodes_available': 'Nodes Available',
  'sale.stage.active': 'Active', 'sale.stage.paused': 'Paused', 'sale.stage.closed': 'Sale Closed', 'sale.current_price': 'Current Price', 'sale.next_price': 'Next Price', 'sale.sold': 'Sold', 'sale.remaining': 'Remaining', 'sale.enter_code': 'Enter referral code', 'sale.select_chain': 'Select Chain', 'sale.select_token': 'Select Payment Token', 'sale.quantity': 'Quantity', 'sale.total': 'Total', 'sale.discount_applied': 'Discount applied: {discount}%',
  'nodes.status.active': 'Active', 'nodes.status.delegated': 'Delegated', 'nodes.status.locked': 'Locked', 'nodes.purchased': 'Purchased', 'nodes.lifetime_rewards': 'Lifetime Rewards', 'nodes.delegated_to': 'Delegated To', 'nodes.total_owned': 'Total Owned', 'nodes.total_rewards': 'Total Rewards',
  'referrals.code': 'Your Referral Code', 'referrals.total': 'Total Referrals', 'referrals.direct': 'Direct Referrals', 'referrals.indirect': 'Indirect Referrals', 'referrals.commission_earned': 'Commission Earned', 'referrals.pending_commission': 'Pending Commission', 'referrals.network': 'Network Overview', 'referrals.milestones': 'Milestones', 'referrals.activity': 'Activity', 'referrals.payouts': 'Payouts', 'referrals.level': 'Level {level}', 'referrals.members': 'Members', 'referrals.sales': 'Sales', 'referrals.commission': 'Commission',
  'tier.affiliate': 'Affiliate', 'tier.partner': 'Partner', 'tier.senior': 'Senior Partner', 'tier.regional': 'Regional Partner', 'tier.market': 'Market Partner', 'tier.founding': 'Founding Partner',
  'payout.pending': 'Pending', 'payout.processing': 'Processing', 'payout.sent': 'Sent', 'payout.confirmed': 'Confirmed', 'payout.failed': 'Failed',
  'event.purchase': 'Node Purchase', 'event.signup': 'New Signup', 'event.tier_promotion': 'Tier Promotion', 'event.milestone': 'Milestone Reached',
  'error.WRONG_CHAIN': 'Please switch to {chain} to continue.', 'error.INSUFFICIENT_BALANCE': 'Insufficient {token} balance. You need {required} but have {available}.', 'error.SALE_CLOSED': 'The node sale is currently closed.', 'error.INVALID_CODE': 'Invalid referral code. Please check and try again.', 'error.ALREADY_REGISTERED': 'This wallet is already registered.', 'error.WALLET_NOT_CONNECTED': 'Please connect your wallet to continue.', 'error.SIGNATURE_REJECTED': 'Signature request was rejected.', 'error.TX_FAILED': 'Transaction failed. Please try again.', 'error.TX_TIMEOUT': 'Transaction timed out. Please check your wallet.', 'error.RATE_LIMITED': 'Too many requests. Please wait a moment.', 'error.UNAUTHORIZED': 'Session expired. Please reconnect your wallet.', 'error.NOT_FOUND': 'The requested resource was not found.', 'error.SERVER_ERROR': 'Something went wrong. Please try again later.', 'error.NETWORK_ERROR': 'Network error. Please check your connection.',
  'empty.nodes': 'You don\'t own any nodes yet. Purchase your first AI agent to get started.', 'empty.referrals': 'No referrals yet. Share your referral code to start earning commissions.', 'empty.activity': 'No activity to show yet.', 'empty.payouts': 'No payouts yet. Commissions will appear here once processed.',
  'misc.loading': 'Loading...', 'misc.powered_by': 'Powered by Operon Network', 'misc.language': 'Language',
} as const;

const pageKeys = {
  'home.welcome': 'Welcome to Operon', 'home.connectPrompt': 'Connect your wallet to access the dashboard', 'home.nodesOwned': 'Nodes Owned', 'home.estDailyEmission': 'Est. Daily Emission', 'home.rewardsAtTge': 'Rewards begin at TGE', 'home.referralNetwork': 'Referral Network', 'home.referrals': 'referrals', 'home.genesisSale': 'Genesis Node Sale', 'home.currentTier': 'Current Tier', 'home.active': 'Active', 'home.paused': 'Paused', 'home.closed': 'Closed', 'home.price': 'Price', 'home.remaining': 'remaining', 'home.totalNodes': 'total nodes', 'home.buyNodes': 'Buy Nodes', 'home.yourReferralCode': 'Your Referral Code', 'home.shareToEarn': 'Share to earn commission', 'home.payoutWallet': 'Payout wallet',
  'sale.referralCode': 'Referral Code', 'sale.codeApplied': 'Applied', 'sale.codeInvalid': 'Invalid', 'sale.tierStatus': 'Tier Status', 'sale.nodesRemaining': 'nodes remaining', 'sale.purchaseDetails': 'Purchase Details', 'sale.chain': 'Chain', 'sale.switchChain': 'Switch to {chain}', 'sale.payWith': 'Pay with', 'sale.balance': 'Balance', 'sale.pricePerNode': 'Price per node', 'sale.connectToBuy': 'Connect wallet to purchase', 'sale.insufficientBalance': 'Insufficient balance', 'sale.approving': 'Approving...', 'sale.approve': 'Approve', 'sale.confirming': 'Confirming...', 'sale.purchase': 'Purchase', 'sale.yourWallet': 'Your wallet', 'sale.purchaseComplete': 'Purchase Complete!', 'sale.youNowOwn': 'You now own {count} Operon Node(s) (Tier {tier})', 'sale.viewNodes': 'View My Nodes', 'sale.buyMore': 'Buy More',
  'nodes.connectWallet': 'Connect wallet to view your nodes', 'nodes.noNodes': 'No Nodes Yet', 'nodes.noNodesDesc': 'Purchase your first node to get started.', 'nodes.goToSale': 'Go to Sale', 'nodes.estDailyEmission': 'Estimated Daily Emission', 'nodes.ownNodes': 'own nodes', 'nodes.referralPool': 'referral pool', 'nodes.owned': 'Owned', 'nodes.invested': 'Invested', 'nodes.chains': 'Chains', 'nodes.inventory': 'Node Inventory', 'nodes.disclaimer': 'Estimates are illustrative. Actual rewards depend on network performance.',
  'nodes.pending.title': 'Purchase confirmed — finalising on backend', 'nodes.pending.body': 'Your purchase tx {tx} is confirmed on-chain. The backend usually finishes attribution within 1–5 minutes; this banner will clear automatically once your node appears.', 'nodes.pending.overdue': 'Taking longer than usual. If this persists past 15 minutes, contact support with the tx hash.',
  'referrals.connectWallet': 'Connect wallet to view referrals', 'referrals.elitePartner': 'Elite Partner', 'referrals.joined': 'Joined', 'referrals.credited': 'Credited', 'referrals.yourCode': 'Your Referral Code', 'referrals.eppShareLabel': 'Your buyers get 15% discount', 'referrals.shareLabel': 'Share to earn commission', 'referrals.tierProgress': 'Tier Progress', 'referrals.commissionByLevel': 'Commission by Level', 'referrals.volume': 'volume', 'referrals.bonus': 'bonus', 'referrals.achieved': 'Achieved', 'referrals.networkBreakdown': 'Network Breakdown', 'referrals.recentActivity': 'Recent Activity', 'referrals.noActivity': 'No activity yet', 'referrals.payoutHistory': 'Payout History', 'referrals.date': 'Date', 'referrals.amount': 'Amount', 'referrals.chain': 'Chain', 'referrals.status': 'Status', 'referrals.noPayouts': 'No payouts yet. Commissions are paid biweekly.', 'referrals.programmeReference': 'Programme Reference', 'referrals.commissionRates': 'Commission Rates', 'referrals.tier': 'Tier', 'referrals.creditedWeights': 'Credited Amount Weights',
  'resources.partnerMaterials': 'Partner Materials', 'resources.pitchManual': 'Pitch Training Manual', 'resources.brandAssets': 'Brand Assets', 'resources.termsConditions': 'Terms & Conditions', 'resources.download': 'Download', 'resources.usefulLinks': 'Useful Links', 'resources.website': 'Website', 'resources.whitepaper': 'Whitepaper', 'resources.faq': 'FAQ', 'resources.medium': 'Medium', 'resources.community': 'Community', 'resources.compliance': 'Compliance', 'resources.complianceNote1': 'Node licenses are participation rights, not securities or investments.', 'resources.complianceNote2': 'Do not publish confidential commission rates or tier thresholds.', 'resources.complianceNote3': 'Use only approved Operon branding materials.', 'resources.complianceNote4': 'Follow all applicable regulations in your jurisdiction.', 'resources.bridgeGuides': 'Bridge Guides', 'resources.bridgeArbitrum': 'Bridge to Arbitrum', 'resources.bridgeBsc': 'Bridge to BNB Chain',
  'sale.saleLive': 'Sale Live', 'sale.gasEstimate': 'Gas est.', 'sale.tierSoldOut': 'Tier Sold Out', 'sale.switchWallet': 'Switch', 'sale.liveUpdates': 'Live updates', 'sale.updatesDelayed': 'Updates may be delayed', 'sale.pendingTx': 'Pending transaction found', 'sale.viewExplorer': 'View on explorer', 'sale.each': 'each', 'sale.bridgeLink': 'Bridge from Ethereum →', 'sale.txSlow': 'Transaction is taking longer than expected.', 'sale.discountLabel': 'Discount ({discount}%)', 'sale.afterDiscount': 'After discount', 'sale.selfReferralWarning': 'Self-referral (using your own code from the same wallet) will invalidate referral rewards.', 'sale.selfReferralBlocked': 'You cannot use your own referral code.', 'sale.noActiveTier': 'No active tier available. Please refresh the page.', 'sale.pendingSync': 'Activating your code on-chain — please try again in a few seconds.', 'sale.maxPerWallet': 'Max 10/wallet', 'sale.priceTimesQty': 'Price × {qty}', 'sale.nodeInfo': '{qty} × ERC-721 NFT on {chain} · 63,000 $OPRN base emission per node', 'sale.walletDisconnected': 'Wallet disconnected. Please reconnect and check your transaction history.', 'sale.networkSlow': 'Network slow — please check your connection', 'sale.codeAppliedToast': 'Referral code applied — {discount}% discount active!', 'sale.allPricesDiscount': 'All prices with {discount}% discount', 'sale.switchTo': 'Switch to {chain}', 'sale.insufficientToken': 'Insufficient {token} balance', 'sale.needToken': 'Need {token}?', 'sale.approveToken': 'Approve {token}', 'sale.purchaseNodes': 'Purchase {qty} Node(s)', 'sale.approvalFailed': 'Approval failed. Please try again.', 'sale.purchaseFailed': 'Purchase failed. Please try again.', 'sale.tierNowActive': 'Tier {tier} is now active', 'sale.tierSoldOutN': 'Tier {tier} is sold out!',
  'auth.signingIn': 'Signing in... please check your wallet', 'auth.signInFailed': 'Sign-in failed',
  'error.pageError': 'Something went wrong', 'error.pageErrorDesc': 'An unexpected error occurred. Please try again or contact support.',
  'nav.overview': 'Overview', 'nav.staking': 'Staking', 'nav.nodeOps': 'Node Ops', 'nav.comingSoon': 'Soon', 'nav.more': 'More',
  'nodeCard.pricePaid': 'Price Paid', 'nodeCard.dailyReward': 'Est. Daily Reward', 'nodeCard.purchased': 'Purchased', 'nodeCard.txHash': 'Tx Hash',
  'btn.dismiss': 'Dismiss', 'btn.buyMoreNodes': 'Buy More Nodes →', 'btn.tryAgain': 'Try again',
  'sale.signInFirst': 'Please complete sign-in first.',
  'referrals.community.title': 'Community Referral Programme', 'referrals.community.subtitle': 'Your buyers get {discount}% off. You earn commission on every sale up to 5 levels deep.', 'referrals.community.tableLevel': 'Level', 'referrals.community.tableYouEarn': 'You earn', 'referrals.community.tableMax': 'Max', 'referrals.community.disclaimer': 'Share your code or link above. Self-referral (using your own code from the same wallet) will invalidate referral rewards.',
  'feed.purchaseSingle': 'L{level} referral purchased 1 node', 'feed.purchasePlural': 'L{level} referral purchased {count} nodes', 'feed.signup': 'New L{level} signup joined your network', 'feed.tierPromotion': 'Promoted to Tier {tier}', 'feed.milestone': 'Milestone reached',
  'feed.justNow': 'just now', 'feed.minAgo': '{n}m ago', 'feed.hrAgo': '{n}h ago', 'feed.dayAgo': '{n}d ago',
  'sale.percentOff': '{discount}% off', 'sale.tierSoldLabel': 'T{tier} Sold', 'sale.soldCountLabel': 'sold', 'sale.codeInvalidBadge': 'Invalid', 'sale.priceTimesQtyLabel': 'Price × {qty}', 'sale.needTokenLabel': 'Need {token}?', 'sale.realtimeOffline': 'Live updates offline — refresh to sync.', 'sale.refreshNow': 'Refresh',
  'home.tierLabel': 'Tier {tier}', 'home.investedLabel': '{amount} invested',
  'sale.tierProgressLine': 'Tier {tier} · {remaining} / {supply} remaining', 'sale.pendingTxSummary': '{qty} node(s) on {chain}',
  'tierBar.tier': 'Tier {tier}', 'tierBar.pricePerNode': '{price} per node', 'tierBar.soldOfSupply': '{sold} / {supply} sold', 'tierBar.currentTier': 'Current Tier',
  'code.copyCode': 'Copy code', 'code.share': 'Share', 'code.copyLink': 'Copy referral link', 'code.shareTitle': 'Operon Node Sale', 'code.shareText': 'Use my referral code: {code}',
} as const;

// ─── Traditional Chinese (繁中) ──────────────────────────────────────────

const tc: Record<keyof typeof en, string> = {
  'nav.home': '儀表板', 'nav.nodes': 'AI 智能體', 'nav.sale': '節點銷售', 'nav.referrals': '推薦網絡', 'nav.settings': '設定', 'nav.docs': '文件', 'nav.support': '支援',
  'btn.connect_wallet': '連接錢包', 'btn.disconnect': '斷開連接', 'btn.buy_now': '立即購買', 'btn.approve': '授權', 'btn.confirm': '確認', 'btn.cancel': '取消', 'btn.copy': '複製', 'btn.copied': '已複製！', 'btn.view_all': '查看全部', 'btn.load_more': '載入更多', 'btn.retry': '重試', 'btn.claim': '領取', 'btn.delegate': '委託', 'btn.share': '分享',
  'page.home.title': '儀表板總覽', 'page.nodes.title': '我的 AI 智能體', 'page.sale.title': '節點銷售', 'page.referrals.title': '推薦網絡', 'page.settings.title': '設定',
  'stats.total_nodes': '節點總數', 'stats.active_nodes': '活躍節點', 'stats.total_earnings': '總收益', 'stats.pending_commissions': '待處理佣金', 'stats.network_size': '網絡規模', 'stats.partner_tier': '合作夥伴等級', 'stats.nodes_available': '可用節點',
  'sale.stage.active': '進行中', 'sale.stage.paused': '暫停', 'sale.stage.closed': '銷售結束', 'sale.current_price': '當前價格', 'sale.next_price': '下一階段價格', 'sale.sold': '已售出', 'sale.remaining': '剩餘', 'sale.enter_code': '輸入推薦碼', 'sale.select_chain': '選擇區塊鏈', 'sale.select_token': '選擇付款代幣', 'sale.quantity': '數量', 'sale.total': '總計', 'sale.discount_applied': '已套用折扣：{discount}%',
  'nodes.status.active': '活躍', 'nodes.status.delegated': '已委託', 'nodes.status.locked': '已鎖定', 'nodes.purchased': '購買時間', 'nodes.lifetime_rewards': '累計獎勵', 'nodes.delegated_to': '委託給', 'nodes.total_owned': '擁有總數', 'nodes.total_rewards': '總獎勵',
  'referrals.code': '您的推薦碼', 'referrals.total': '推薦總數', 'referrals.direct': '直接推薦', 'referrals.indirect': '間接推薦', 'referrals.commission_earned': '已賺取佣金', 'referrals.pending_commission': '待處理佣金', 'referrals.network': '網絡概覽', 'referrals.milestones': '里程碑', 'referrals.activity': '活動', 'referrals.payouts': '付款記錄', 'referrals.level': '第 {level} 層', 'referrals.members': '成員', 'referrals.sales': '銷售額', 'referrals.commission': '佣金',
  'tier.affiliate': '聯盟夥伴', 'tier.partner': '合作夥伴', 'tier.senior': '高級合作夥伴', 'tier.regional': '區域合作夥伴', 'tier.market': '市場合作夥伴', 'tier.founding': '創始合作夥伴',
  'payout.pending': '待處理', 'payout.processing': '處理中', 'payout.sent': '已發送', 'payout.confirmed': '已確認', 'payout.failed': '失敗',
  'event.purchase': '節點購買', 'event.signup': '新註冊', 'event.tier_promotion': '等級晉升', 'event.milestone': '達成里程碑',
  'error.WRONG_CHAIN': '請切換到 {chain} 以繼續。', 'error.INSUFFICIENT_BALANCE': '{token} 餘額不足。您需要 {required}，但僅有 {available}。', 'error.SALE_CLOSED': '節點銷售目前已關閉。', 'error.INVALID_CODE': '無效的推薦碼，請檢查後重試。', 'error.ALREADY_REGISTERED': '此錢包已註冊。', 'error.WALLET_NOT_CONNECTED': '請連接錢包以繼續。', 'error.SIGNATURE_REJECTED': '簽名請求已被拒絕。', 'error.TX_FAILED': '交易失敗，請重試。', 'error.TX_TIMEOUT': '交易超時，請檢查您的錢包。', 'error.RATE_LIMITED': '請求過於頻繁，請稍後再試。', 'error.UNAUTHORIZED': '會話已過期，請重新連接錢包。', 'error.NOT_FOUND': '找不到請求的資源。', 'error.SERVER_ERROR': '發生錯誤，請稍後再試。', 'error.NETWORK_ERROR': '網絡錯誤，請檢查您的連接。',
  'empty.nodes': '您尚未擁有任何節點。購買您的第一個 AI 智能體以開始使用。', 'empty.referrals': '尚無推薦。分享您的推薦碼以開始賺取佣金。', 'empty.activity': '尚無活動記錄。', 'empty.payouts': '尚無付款記錄。佣金處理完成後將顯示在此處。',
  'misc.loading': '載入中...', 'misc.powered_by': '由 Operon Network 提供支持', 'misc.language': '語言',
};

const pageKeysTc: Record<keyof typeof pageKeys, string> = {
  'home.welcome': '歡迎來到 Operon', 'home.connectPrompt': '連接您的錢包以訪問儀表板', 'home.nodesOwned': '擁有節點', 'home.estDailyEmission': '預計每日排放', 'home.rewardsAtTge': '獎勵將於 TGE 時開始', 'home.referralNetwork': '推薦網絡', 'home.referrals': '推薦', 'home.genesisSale': '創世節點銷售', 'home.currentTier': '當前層級', 'home.active': '進行中', 'home.paused': '暫停', 'home.closed': '已結束', 'home.price': '價格', 'home.remaining': '剩餘', 'home.totalNodes': '節點總數', 'home.buyNodes': '購買節點', 'home.yourReferralCode': '您的推薦碼', 'home.shareToEarn': '分享以賺取佣金', 'home.payoutWallet': '付款錢包',
  'sale.referralCode': '推薦碼', 'sale.codeApplied': '已套用', 'sale.codeInvalid': '無效', 'sale.tierStatus': '層級狀態', 'sale.nodesRemaining': '節點剩餘', 'sale.purchaseDetails': '購買詳情', 'sale.chain': '區塊鏈', 'sale.switchChain': '切換到 {chain}', 'sale.payWith': '付款方式', 'sale.balance': '餘額', 'sale.pricePerNode': '每節點價格', 'sale.connectToBuy': '連接錢包以購買', 'sale.insufficientBalance': '餘額不足', 'sale.approving': '授權中...', 'sale.approve': '授權', 'sale.confirming': '確認中...', 'sale.purchase': '購買', 'sale.yourWallet': '您的錢包', 'sale.purchaseComplete': '購買完成！', 'sale.youNowOwn': '您現在擁有 {count} 個 Operon 節點（第 {tier} 層）', 'sale.viewNodes': '查看我的節點', 'sale.buyMore': '購買更多',
  'nodes.connectWallet': '連接錢包以查看您的節點', 'nodes.noNodes': '尚無節點', 'nodes.noNodesDesc': '購買您的第一個節點以開始使用。', 'nodes.goToSale': '前往銷售', 'nodes.estDailyEmission': '預計每日排放', 'nodes.ownNodes': '自有節點', 'nodes.referralPool': '推薦池', 'nodes.owned': '擁有', 'nodes.invested': '已投入', 'nodes.chains': '鏈', 'nodes.inventory': '節點清單', 'nodes.disclaimer': '估算僅供參考。實際獎勵取決於網絡表現。',
  'nodes.pending.title': '購買已確認 — 後端處理中', 'nodes.pending.body': '您的交易 {tx} 已在鏈上確認。後端通常會於 1–5 分鐘內完成歸屬，您的節點出現後此提示將自動消失。', 'nodes.pending.overdue': '時間比預期長。若超過 15 分鐘仍未完成，請附上交易雜湊聯繫客服。',
  'referrals.connectWallet': '連接錢包以查看推薦', 'referrals.elitePartner': '菁英合作夥伴', 'referrals.joined': '加入日期', 'referrals.credited': '歸功金額', 'referrals.yourCode': '您的推薦碼', 'referrals.eppShareLabel': '您的買家享 85 折優惠', 'referrals.shareLabel': '分享以賺取佣金', 'referrals.tierProgress': '等級進度', 'referrals.commissionByLevel': '各層級佣金', 'referrals.volume': '銷售額', 'referrals.bonus': '獎金', 'referrals.achieved': '已達成', 'referrals.networkBreakdown': '網絡明細', 'referrals.recentActivity': '近期活動', 'referrals.noActivity': '尚無活動', 'referrals.payoutHistory': '付款歷史', 'referrals.date': '日期', 'referrals.amount': '金額', 'referrals.chain': '鏈', 'referrals.status': '狀態', 'referrals.noPayouts': '尚無付款。佣金每兩週發放一次。', 'referrals.programmeReference': '計畫參考', 'referrals.commissionRates': '佣金費率', 'referrals.tier': '層級', 'referrals.creditedWeights': '歸功金額權重',
  'resources.partnerMaterials': '合作夥伴資料', 'resources.pitchManual': '銷售培訓手冊', 'resources.brandAssets': '品牌素材', 'resources.termsConditions': '條款與細則', 'resources.download': '下載', 'resources.usefulLinks': '實用連結', 'resources.website': '官網', 'resources.whitepaper': '白皮書', 'resources.faq': '常見問題', 'resources.medium': 'Medium', 'resources.community': '社群', 'resources.compliance': '合規', 'resources.complianceNote1': '節點許可為參與權利，非證券或投資。', 'resources.complianceNote2': '請勿公開保密的佣金費率或層級門檻。', 'resources.complianceNote3': '僅使用經批准的 Operon 品牌素材。', 'resources.complianceNote4': '遵守您所在地區的所有適用法規。', 'resources.bridgeGuides': '跨鏈指南', 'resources.bridgeArbitrum': '跨鏈至 Arbitrum', 'resources.bridgeBsc': '跨鏈至 BNB Chain',
  'sale.saleLive': '銷售中', 'sale.gasEstimate': 'Gas 預估', 'sale.tierSoldOut': '該層級已售罄', 'sale.switchWallet': '切換', 'sale.liveUpdates': '即時更新', 'sale.updatesDelayed': '更新可能有延遲', 'sale.pendingTx': '發現待處理交易', 'sale.viewExplorer': '在區塊瀏覽器查看', 'sale.each': '每個', 'sale.bridgeLink': '從以太坊跨鏈 →', 'sale.txSlow': '交易時間超過預期。', 'sale.discountLabel': '折扣（{discount}%）', 'sale.afterDiscount': '折後價', 'sale.selfReferralWarning': '使用同一錢包以自己的推薦碼進行自我推薦將使推薦獎勵失效。', 'sale.selfReferralBlocked': '無法使用自己的推薦碼。', 'sale.noActiveTier': '目前沒有可用的銷售層級，請重新整理頁面。', 'sale.pendingSync': '正在將您的推薦碼同步到鏈上，請稍候幾秒再試。',
  'sale.walletDisconnected': '錢包已斷開連接，請重新連接並檢查交易歷史。', 'sale.networkSlow': '網絡速度較慢 — 請檢查您的連接', 'sale.codeAppliedToast': '推薦碼已套用 — {discount}% 折扣已生效！', 'sale.maxPerWallet': '每個錢包最多 10 個', 'sale.approvalFailed': '授權失敗，請重試。', 'sale.purchaseFailed': '購買失敗，請重試。', 'sale.tierSoldOutN': '第 {tier} 層已售罄！', 'sale.tierNowActive': '第 {tier} 層現正銷售', 'sale.switchTo': '切換到 {chain}', 'sale.needToken': '需要 {token}？', 'sale.approveToken': '授權 {token}', 'sale.purchaseNodes': '購買 {qty} 個節點', 'sale.insufficientToken': '{token} 餘額不足', 'sale.priceTimesQty': '價格 × {qty}', 'sale.nodeInfo': '{qty} × ERC-721 NFT，於 {chain} · 每節點基礎發行 63,000 $OPRN', 'sale.allPricesDiscount': '所有價格含 {discount}% 折扣',
  'auth.signingIn': '正在登入...請檢查您的錢包', 'auth.signInFailed': '登入失敗',
  'error.pageError': '出現問題', 'error.pageErrorDesc': '發生意外錯誤。請重試或聯繫客服。',
  'nav.overview': '總覽', 'nav.staking': '質押', 'nav.nodeOps': '節點操作', 'nav.comingSoon': '即將推出', 'nav.more': '更多',
  'nodeCard.pricePaid': '支付價格', 'nodeCard.dailyReward': '預估每日獎勵', 'nodeCard.purchased': '購買日期', 'nodeCard.txHash': '交易雜湊',
  'btn.dismiss': '關閉', 'btn.buyMoreNodes': '購買更多節點 →', 'btn.tryAgain': '重試',
  'sale.signInFirst': '請先完成登入。',
  'referrals.community.title': '社群推薦計畫', 'referrals.community.subtitle': '您的買家享 {discount}% 折扣，您在最多 5 層推薦鏈中均可賺取佣金。', 'referrals.community.tableLevel': '層級', 'referrals.community.tableYouEarn': '您賺取', 'referrals.community.tableMax': '上限', 'referrals.community.disclaimer': '分享您的推薦碼或連結。自我推薦（以同一錢包使用自己的推薦碼）將使推薦獎勵失效。',
  'feed.purchaseSingle': 'L{level} 推薦用戶購買 1 個節點', 'feed.purchasePlural': 'L{level} 推薦用戶購買 {count} 個節點', 'feed.signup': '新的 L{level} 推薦用戶加入您的網絡', 'feed.tierPromotion': '晉升至第 {tier} 層', 'feed.milestone': '達成里程碑',
  'feed.justNow': '剛剛', 'feed.minAgo': '{n} 分鐘前', 'feed.hrAgo': '{n} 小時前', 'feed.dayAgo': '{n} 天前',
  'sale.percentOff': '{discount}% 折扣', 'sale.tierSoldLabel': '第 {tier} 層已售罄', 'sale.soldCountLabel': '已售', 'sale.codeInvalidBadge': '無效', 'sale.priceTimesQtyLabel': '價格 × {qty}', 'sale.needTokenLabel': '需要 {token}？', 'sale.realtimeOffline': '即時更新已離線 — 請重新整理以同步。', 'sale.refreshNow': '重新整理',
  'home.tierLabel': '第 {tier} 層', 'home.investedLabel': '已投資 {amount}',
  'sale.tierProgressLine': '第 {tier} 層 · 剩餘 {remaining} / {supply}', 'sale.pendingTxSummary': '{qty} 個節點，於 {chain}',
  'tierBar.tier': '第 {tier} 層', 'tierBar.pricePerNode': '每節點 {price}', 'tierBar.soldOfSupply': '已售 {sold} / {supply}', 'tierBar.currentTier': '當前層級',
  'code.copyCode': '複製代碼', 'code.share': '分享', 'code.copyLink': '複製推薦連結', 'code.shareTitle': 'Operon 節點銷售', 'code.shareText': '請使用我的推薦碼：{code}',
};

// ─── Simplified Chinese (简中) ───────────────────────────────────────────

const sc: Record<keyof typeof en, string> = {
  'nav.home': '仪表板', 'nav.nodes': 'AI 智能体', 'nav.sale': '节点销售', 'nav.referrals': '推荐网络', 'nav.settings': '设置', 'nav.docs': '文档', 'nav.support': '支持',
  'btn.connect_wallet': '连接钱包', 'btn.disconnect': '断开连接', 'btn.buy_now': '立即购买', 'btn.approve': '授权', 'btn.confirm': '确认', 'btn.cancel': '取消', 'btn.copy': '复制', 'btn.copied': '已复制！', 'btn.view_all': '查看全部', 'btn.load_more': '加载更多', 'btn.retry': '重试', 'btn.claim': '领取', 'btn.delegate': '委托', 'btn.share': '分享',
  'page.home.title': '仪表板概览', 'page.nodes.title': '我的 AI 智能体', 'page.sale.title': '节点销售', 'page.referrals.title': '推荐网络', 'page.settings.title': '设置',
  'stats.total_nodes': '节点总数', 'stats.active_nodes': '活跃节点', 'stats.total_earnings': '总收益', 'stats.pending_commissions': '待处理佣金', 'stats.network_size': '网络规模', 'stats.partner_tier': '合作伙伴等级', 'stats.nodes_available': '可用节点',
  'sale.stage.active': '进行中', 'sale.stage.paused': '暂停', 'sale.stage.closed': '销售结束', 'sale.current_price': '当前价格', 'sale.next_price': '下一阶段价格', 'sale.sold': '已售出', 'sale.remaining': '剩余', 'sale.enter_code': '输入推荐码', 'sale.select_chain': '选择区块链', 'sale.select_token': '选择付款代币', 'sale.quantity': '数量', 'sale.total': '总计', 'sale.discount_applied': '已应用折扣：{discount}%',
  'nodes.status.active': '活跃', 'nodes.status.delegated': '已委托', 'nodes.status.locked': '已锁定', 'nodes.purchased': '购买时间', 'nodes.lifetime_rewards': '累计奖励', 'nodes.delegated_to': '委托给', 'nodes.total_owned': '拥有总数', 'nodes.total_rewards': '总奖励',
  'referrals.code': '您的推荐码', 'referrals.total': '推荐总数', 'referrals.direct': '直接推荐', 'referrals.indirect': '间接推荐', 'referrals.commission_earned': '已赚取佣金', 'referrals.pending_commission': '待处理佣金', 'referrals.network': '网络概览', 'referrals.milestones': '里程碑', 'referrals.activity': '活动', 'referrals.payouts': '付款记录', 'referrals.level': '第 {level} 层', 'referrals.members': '成员', 'referrals.sales': '销售额', 'referrals.commission': '佣金',
  'tier.affiliate': '联盟伙伴', 'tier.partner': '合作伙伴', 'tier.senior': '高级合作伙伴', 'tier.regional': '区域合作伙伴', 'tier.market': '市场合作伙伴', 'tier.founding': '创始合作伙伴',
  'payout.pending': '待处理', 'payout.processing': '处理中', 'payout.sent': '已发送', 'payout.confirmed': '已确认', 'payout.failed': '失败',
  'event.purchase': '节点购买', 'event.signup': '新注册', 'event.tier_promotion': '等级晋升', 'event.milestone': '达成里程碑',
  'error.WRONG_CHAIN': '请切换到 {chain} 以继续。', 'error.INSUFFICIENT_BALANCE': '{token} 余额不足。您需要 {required}，但仅有 {available}。', 'error.SALE_CLOSED': '节点销售目前已关闭。', 'error.INVALID_CODE': '无效的推荐码，请检查后重试。', 'error.ALREADY_REGISTERED': '此钱包已注册。', 'error.WALLET_NOT_CONNECTED': '请连接钱包以继续。', 'error.SIGNATURE_REJECTED': '签名请求已被拒绝。', 'error.TX_FAILED': '交易失败，请重试。', 'error.TX_TIMEOUT': '交易超时，请检查您的钱包。', 'error.RATE_LIMITED': '请求过于频繁，请稍后再试。', 'error.UNAUTHORIZED': '会话已过期，请重新连接钱包。', 'error.NOT_FOUND': '找不到请求的资源。', 'error.SERVER_ERROR': '发生错误，请稍后再试。', 'error.NETWORK_ERROR': '网络错误，请检查您的连接。',
  'empty.nodes': '您尚未拥有任何节点。购买您的第一个 AI 智能体以开始使用。', 'empty.referrals': '尚无推荐。分享您的推荐码以开始赚取佣金。', 'empty.activity': '尚无活动记录。', 'empty.payouts': '尚无付款记录。佣金处理完成后将显示在此处。',
  'misc.loading': '加载中...', 'misc.powered_by': '由 Operon Network 提供支持', 'misc.language': '语言',
};

const pageKeysSc: Record<keyof typeof pageKeys, string> = {
  'home.welcome': '欢迎来到 Operon', 'home.connectPrompt': '连接您的钱包以访问仪表板', 'home.nodesOwned': '拥有节点', 'home.estDailyEmission': '预计每日排放', 'home.rewardsAtTge': '奖励将于 TGE 时开始', 'home.referralNetwork': '推荐网络', 'home.referrals': '推荐', 'home.genesisSale': '创世节点销售', 'home.currentTier': '当前层级', 'home.active': '进行中', 'home.paused': '暂停', 'home.closed': '已结束', 'home.price': '价格', 'home.remaining': '剩余', 'home.totalNodes': '节点总数', 'home.buyNodes': '购买节点', 'home.yourReferralCode': '您的推荐码', 'home.shareToEarn': '分享以赚取佣金', 'home.payoutWallet': '付款钱包',
  'sale.referralCode': '推荐码', 'sale.codeApplied': '已应用', 'sale.codeInvalid': '无效', 'sale.tierStatus': '层级状态', 'sale.nodesRemaining': '节点剩余', 'sale.purchaseDetails': '购买详情', 'sale.chain': '区块链', 'sale.switchChain': '切换到 {chain}', 'sale.payWith': '付款方式', 'sale.balance': '余额', 'sale.pricePerNode': '每节点价格', 'sale.connectToBuy': '连接钱包以购买', 'sale.insufficientBalance': '余额不足', 'sale.approving': '授权中...', 'sale.approve': '授权', 'sale.confirming': '确认中...', 'sale.purchase': '购买', 'sale.yourWallet': '您的钱包', 'sale.purchaseComplete': '购买完成！', 'sale.youNowOwn': '您现在拥有 {count} 个 Operon 节点（第 {tier} 层）', 'sale.viewNodes': '查看我的节点', 'sale.buyMore': '购买更多',
  'nodes.connectWallet': '连接钱包以查看您的节点', 'nodes.noNodes': '尚无节点', 'nodes.noNodesDesc': '购买您的第一个节点以开始使用。', 'nodes.goToSale': '前往销售', 'nodes.estDailyEmission': '预计每日排放', 'nodes.ownNodes': '自有节点', 'nodes.referralPool': '推荐池', 'nodes.owned': '拥有', 'nodes.invested': '已投入', 'nodes.chains': '链', 'nodes.inventory': '节点清单', 'nodes.disclaimer': '估算仅供参考。实际奖励取决于网络表现。',
  'nodes.pending.title': '购买已确认 — 后端处理中', 'nodes.pending.body': '您的交易 {tx} 已在链上确认。后端通常会于 1–5 分钟内完成归属，您的节点出现后此提示将自动消失。', 'nodes.pending.overdue': '时间比预期长。若超过 15 分钟仍未完成，请附上交易哈希联系客服。',
  'referrals.connectWallet': '连接钱包以查看推荐', 'referrals.elitePartner': '精英合作伙伴', 'referrals.joined': '加入日期', 'referrals.credited': '归功金额', 'referrals.yourCode': '您的推荐码', 'referrals.eppShareLabel': '您的买家享 85 折优惠', 'referrals.shareLabel': '分享以赚取佣金', 'referrals.tierProgress': '等级进度', 'referrals.commissionByLevel': '各层级佣金', 'referrals.volume': '销售额', 'referrals.bonus': '奖金', 'referrals.achieved': '已达成', 'referrals.networkBreakdown': '网络明细', 'referrals.recentActivity': '近期活动', 'referrals.noActivity': '尚无活动', 'referrals.payoutHistory': '付款历史', 'referrals.date': '日期', 'referrals.amount': '金额', 'referrals.chain': '链', 'referrals.status': '状态', 'referrals.noPayouts': '尚无付款。佣金每两周发放一次。', 'referrals.programmeReference': '计划参考', 'referrals.commissionRates': '佣金费率', 'referrals.tier': '层级', 'referrals.creditedWeights': '归功金额权重',
  'resources.partnerMaterials': '合作伙伴资料', 'resources.pitchManual': '销售培训手册', 'resources.brandAssets': '品牌素材', 'resources.termsConditions': '条款与细则', 'resources.download': '下载', 'resources.usefulLinks': '实用链接', 'resources.website': '官网', 'resources.whitepaper': '白皮书', 'resources.faq': '常见问题', 'resources.medium': 'Medium', 'resources.community': '社区', 'resources.compliance': '合规', 'resources.complianceNote1': '节点许可为参与权利，非证券或投资。', 'resources.complianceNote2': '请勿公开保密的佣金费率或层级门槛。', 'resources.complianceNote3': '仅使用经批准的 Operon 品牌素材。', 'resources.complianceNote4': '遵守您所在地区的所有适用法规。', 'resources.bridgeGuides': '跨链指南', 'resources.bridgeArbitrum': '跨链至 Arbitrum', 'resources.bridgeBsc': '跨链至 BNB Chain',
  'sale.saleLive': '销售中', 'sale.gasEstimate': 'Gas 预估', 'sale.tierSoldOut': '该层级已售罄', 'sale.switchWallet': '切换', 'sale.liveUpdates': '实时更新', 'sale.updatesDelayed': '更新可能有延迟', 'sale.pendingTx': '发现待处理交易', 'sale.viewExplorer': '在区块浏览器查看', 'sale.each': '每个', 'sale.bridgeLink': '从以太坊跨链 →', 'sale.txSlow': '交易时间超过预期。', 'sale.discountLabel': '折扣（{discount}%）', 'sale.afterDiscount': '折后价', 'sale.selfReferralWarning': '使用同一钱包以自己的推荐码进行自我推荐将使推荐奖励失效。', 'sale.selfReferralBlocked': '无法使用自己的推荐码。', 'sale.noActiveTier': '目前没有可用的销售层级，请刷新页面。', 'sale.pendingSync': '正在将您的推荐码同步到链上，请稍候几秒再试。',
  'sale.walletDisconnected': '钱包已断开连接，请重新连接并检查交易历史。', 'sale.networkSlow': '网络速度较慢 — 请检查您的连接', 'sale.codeAppliedToast': '推荐码已应用 — {discount}% 折扣已生效！', 'sale.maxPerWallet': '每个钱包最多 10 个', 'sale.approvalFailed': '授权失败，请重试。', 'sale.purchaseFailed': '购买失败，请重试。', 'sale.tierSoldOutN': '第 {tier} 层已售罄！', 'sale.tierNowActive': '第 {tier} 层现正销售', 'sale.switchTo': '切换到 {chain}', 'sale.needToken': '需要 {token}？', 'sale.approveToken': '授权 {token}', 'sale.purchaseNodes': '购买 {qty} 个节点', 'sale.insufficientToken': '{token} 余额不足', 'sale.priceTimesQty': '价格 × {qty}', 'sale.nodeInfo': '{qty} × ERC-721 NFT，于 {chain} · 每节点基础发行 63,000 $OPRN', 'sale.allPricesDiscount': '所有价格含 {discount}% 折扣',
  'auth.signingIn': '正在登录...请检查您的钱包', 'auth.signInFailed': '登录失败',
  'error.pageError': '出现问题', 'error.pageErrorDesc': '发生意外错误。请重试或联系客服。',
  'nav.overview': '概览', 'nav.staking': '质押', 'nav.nodeOps': '节点操作', 'nav.comingSoon': '即将推出', 'nav.more': '更多',
  'nodeCard.pricePaid': '支付价格', 'nodeCard.dailyReward': '预估每日奖励', 'nodeCard.purchased': '购买日期', 'nodeCard.txHash': '交易哈希',
  'btn.dismiss': '关闭', 'btn.buyMoreNodes': '购买更多节点 →', 'btn.tryAgain': '重试',
  'sale.signInFirst': '请先完成登录。',
  'referrals.community.title': '社区推荐计划', 'referrals.community.subtitle': '您的买家享 {discount}% 折扣，您在最多 5 层推荐链中均可赚取佣金。', 'referrals.community.tableLevel': '层级', 'referrals.community.tableYouEarn': '您赚取', 'referrals.community.tableMax': '上限', 'referrals.community.disclaimer': '分享您的推荐码或链接。自我推荐（以同一钱包使用自己的推荐码）将使推荐奖励失效。',
  'feed.purchaseSingle': 'L{level} 推荐用户购买 1 个节点', 'feed.purchasePlural': 'L{level} 推荐用户购买 {count} 个节点', 'feed.signup': '新的 L{level} 推荐用户加入您的网络', 'feed.tierPromotion': '晋升至第 {tier} 层', 'feed.milestone': '达成里程碑',
  'feed.justNow': '刚刚', 'feed.minAgo': '{n} 分钟前', 'feed.hrAgo': '{n} 小时前', 'feed.dayAgo': '{n} 天前',
  'sale.percentOff': '{discount}% 折扣', 'sale.tierSoldLabel': '第 {tier} 层已售罄', 'sale.soldCountLabel': '已售', 'sale.codeInvalidBadge': '无效', 'sale.priceTimesQtyLabel': '价格 × {qty}', 'sale.needTokenLabel': '需要 {token}？', 'sale.realtimeOffline': '实时更新已离线 — 请刷新以同步。', 'sale.refreshNow': '刷新',
  'home.tierLabel': '第 {tier} 层', 'home.investedLabel': '已投资 {amount}',
  'sale.tierProgressLine': '第 {tier} 层 · 剩余 {remaining} / {supply}', 'sale.pendingTxSummary': '{qty} 个节点，于 {chain}',
  'tierBar.tier': '第 {tier} 层', 'tierBar.pricePerNode': '每节点 {price}', 'tierBar.soldOfSupply': '已售 {sold} / {supply}', 'tierBar.currentTier': '当前层级',
  'code.copyCode': '复制代码', 'code.share': '分享', 'code.copyLink': '复制推荐链接', 'code.shareTitle': 'Operon 节点销售', 'code.shareText': '请使用我的推荐码：{code}',
};

// ─── Korean (한국어) ─────────────────────────────────────────────────────

const ko: Record<keyof typeof en, string> = {
  'nav.home': '대시보드', 'nav.nodes': 'AI 에이전트', 'nav.sale': '노드 판매', 'nav.referrals': '추천', 'nav.settings': '설정', 'nav.docs': '문서', 'nav.support': '지원',
  'btn.connect_wallet': '지갑 연결', 'btn.disconnect': '연결 해제', 'btn.buy_now': '지금 구매', 'btn.approve': '승인', 'btn.confirm': '확인', 'btn.cancel': '취소', 'btn.copy': '복사', 'btn.copied': '복사됨!', 'btn.view_all': '전체 보기', 'btn.load_more': '더 불러오기', 'btn.retry': '재시도', 'btn.claim': '청구', 'btn.delegate': '위임', 'btn.share': '공유',
  'page.home.title': '대시보드 개요', 'page.nodes.title': '내 AI 에이전트', 'page.sale.title': '노드 판매', 'page.referrals.title': '추천 네트워크', 'page.settings.title': '설정',
  'stats.total_nodes': '총 노드', 'stats.active_nodes': '활성 노드', 'stats.total_earnings': '총 수익', 'stats.pending_commissions': '대기 중 커미션', 'stats.network_size': '네트워크 규모', 'stats.partner_tier': '파트너 등급', 'stats.nodes_available': '구매 가능 노드',
  'sale.stage.active': '활성', 'sale.stage.paused': '일시정지', 'sale.stage.closed': '판매 종료', 'sale.current_price': '현재 가격', 'sale.next_price': '다음 가격', 'sale.sold': '판매됨', 'sale.remaining': '잔여', 'sale.enter_code': '추천 코드 입력', 'sale.select_chain': '체인 선택', 'sale.select_token': '결제 토큰 선택', 'sale.quantity': '수량', 'sale.total': '합계', 'sale.discount_applied': '할인 적용: {discount}%',
  'nodes.status.active': '활성', 'nodes.status.delegated': '위임됨', 'nodes.status.locked': '잠금', 'nodes.purchased': '구매일', 'nodes.lifetime_rewards': '누적 보상', 'nodes.delegated_to': '위임 대상', 'nodes.total_owned': '총 보유', 'nodes.total_rewards': '총 보상',
  'referrals.code': '내 추천 코드', 'referrals.total': '총 추천', 'referrals.direct': '직접 추천', 'referrals.indirect': '간접 추천', 'referrals.commission_earned': '획득 커미션', 'referrals.pending_commission': '대기 중 커미션', 'referrals.network': '네트워크 개요', 'referrals.milestones': '마일스톤', 'referrals.activity': '활동', 'referrals.payouts': '지급 내역', 'referrals.level': '레벨 {level}', 'referrals.members': '멤버', 'referrals.sales': '판매', 'referrals.commission': '커미션',
  'tier.affiliate': '어필리에이트', 'tier.partner': '파트너', 'tier.senior': '시니어 파트너', 'tier.regional': '리전 파트너', 'tier.market': '마켓 파트너', 'tier.founding': '파운딩 파트너',
  'payout.pending': '대기 중', 'payout.processing': '처리 중', 'payout.sent': '전송됨', 'payout.confirmed': '확인됨', 'payout.failed': '실패',
  'event.purchase': '노드 구매', 'event.signup': '신규 가입', 'event.tier_promotion': '등급 승격', 'event.milestone': '마일스톤 달성',
  'error.WRONG_CHAIN': '계속하려면 {chain}으로 전환해 주세요.', 'error.INSUFFICIENT_BALANCE': '{token} 잔액이 부족합니다. {required}이 필요하지만 {available}만 보유 중입니다.', 'error.SALE_CLOSED': '노드 판매가 현재 종료되었습니다.', 'error.INVALID_CODE': '유효하지 않은 추천 코드입니다. 확인 후 다시 시도해 주세요.', 'error.ALREADY_REGISTERED': '이 지갑은 이미 등록되어 있습니다.', 'error.WALLET_NOT_CONNECTED': '계속하려면 지갑을 연결해 주세요.', 'error.SIGNATURE_REJECTED': '서명 요청이 거부되었습니다.', 'error.TX_FAILED': '트랜잭션이 실패했습니다. 다시 시도해 주세요.', 'error.TX_TIMEOUT': '트랜잭션 시간이 초과되었습니다. 지갑을 확인해 주세요.', 'error.RATE_LIMITED': '요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.', 'error.UNAUTHORIZED': '세션이 만료되었습니다. 지갑을 다시 연결해 주세요.', 'error.NOT_FOUND': '요청한 리소스를 찾을 수 없습니다.', 'error.SERVER_ERROR': '문제가 발생했습니다. 나중에 다시 시도해 주세요.', 'error.NETWORK_ERROR': '네트워크 오류입니다. 연결을 확인해 주세요.',
  'empty.nodes': '아직 보유한 노드가 없습니다. 첫 AI 에이전트를 구매하여 시작하세요.', 'empty.referrals': '아직 추천이 없습니다. 추천 코드를 공유하여 커미션을 받으세요.', 'empty.activity': '아직 표시할 활동이 없습니다.', 'empty.payouts': '아직 지급 내역이 없습니다. 커미션이 처리되면 여기에 표시됩니다.',
  'misc.loading': '로딩 중...', 'misc.powered_by': 'Operon Network 제공', 'misc.language': '언어',
};

const pageKeysKo: Record<keyof typeof pageKeys, string> = {
  'home.welcome': 'Operon에 오신 것을 환영합니다', 'home.connectPrompt': '대시보드에 접속하려면 지갑을 연결하세요', 'home.nodesOwned': '보유 노드', 'home.estDailyEmission': '예상 일일 배출량', 'home.rewardsAtTge': 'TGE 시 보상 시작', 'home.referralNetwork': '추천 네트워크', 'home.referrals': '추천', 'home.genesisSale': '제네시스 노드 판매', 'home.currentTier': '현재 등급', 'home.active': '활성', 'home.paused': '일시정지', 'home.closed': '종료', 'home.price': '가격', 'home.remaining': '잔여', 'home.totalNodes': '총 노드', 'home.buyNodes': '노드 구매', 'home.yourReferralCode': '내 추천 코드', 'home.shareToEarn': '공유하여 커미션 받기', 'home.payoutWallet': '지급 지갑',
  'sale.referralCode': '추천 코드', 'sale.codeApplied': '적용됨', 'sale.codeInvalid': '유효하지 않음', 'sale.tierStatus': '등급 현황', 'sale.nodesRemaining': '노드 잔여', 'sale.purchaseDetails': '구매 상세', 'sale.chain': '체인', 'sale.switchChain': '{chain}으로 전환', 'sale.payWith': '결제 수단', 'sale.balance': '잔액', 'sale.pricePerNode': '노드당 가격', 'sale.connectToBuy': '구매하려면 지갑 연결', 'sale.insufficientBalance': '잔액 부족', 'sale.approving': '승인 중...', 'sale.approve': '승인', 'sale.confirming': '확인 중...', 'sale.purchase': '구매', 'sale.yourWallet': '내 지갑', 'sale.purchaseComplete': '구매 완료!', 'sale.youNowOwn': 'Operon 노드 {count}개를 보유합니다 (등급 {tier})', 'sale.viewNodes': '내 노드 보기', 'sale.buyMore': '더 구매',
  'nodes.connectWallet': '노드를 보려면 지갑을 연결하세요', 'nodes.noNodes': '아직 노드 없음', 'nodes.noNodesDesc': '첫 노드를 구매하여 시작하세요.', 'nodes.goToSale': '판매로 이동', 'nodes.estDailyEmission': '예상 일일 배출량', 'nodes.ownNodes': '자체 노드', 'nodes.referralPool': '추천 풀', 'nodes.owned': '보유', 'nodes.invested': '투자액', 'nodes.chains': '체인', 'nodes.inventory': '노드 목록', 'nodes.disclaimer': '추정치는 예시입니다. 실제 보상은 네트워크 성능에 따라 달라집니다.',
  'nodes.pending.title': '구매 확인됨 — 백엔드 처리 중', 'nodes.pending.body': '거래 {tx}가 온체인에서 확인되었습니다. 백엔드가 일반적으로 1–5분 내에 귀속을 완료합니다. 노드가 표시되면 이 알림은 자동으로 사라집니다.', 'nodes.pending.overdue': '예상보다 오래 걸리고 있습니다. 15분이 지나도 완료되지 않으면 거래 해시와 함께 지원팀에 문의하세요.',
  'referrals.connectWallet': '추천을 보려면 지갑 연결', 'referrals.elitePartner': '엘리트 파트너', 'referrals.joined': '가입일', 'referrals.credited': '기여 금액', 'referrals.yourCode': '내 추천 코드', 'referrals.eppShareLabel': '구매자 15% 할인', 'referrals.shareLabel': '공유하여 커미션 받기', 'referrals.tierProgress': '등급 진행', 'referrals.commissionByLevel': '레벨별 커미션', 'referrals.volume': '거래량', 'referrals.bonus': '보너스', 'referrals.achieved': '달성', 'referrals.networkBreakdown': '네트워크 내역', 'referrals.recentActivity': '최근 활동', 'referrals.noActivity': '아직 활동 없음', 'referrals.payoutHistory': '지급 이력', 'referrals.date': '날짜', 'referrals.amount': '금액', 'referrals.chain': '체인', 'referrals.status': '상태', 'referrals.noPayouts': '아직 지급 내역 없음. 커미션은 격주 지급됩니다.', 'referrals.programmeReference': '프로그램 참고', 'referrals.commissionRates': '커미션 요율', 'referrals.tier': '등급', 'referrals.creditedWeights': '기여 금액 가중치',
  'resources.partnerMaterials': '파트너 자료', 'resources.pitchManual': '영업 교육 매뉴얼', 'resources.brandAssets': '브랜드 자산', 'resources.termsConditions': '이용 약관', 'resources.download': '다운로드', 'resources.usefulLinks': '유용한 링크', 'resources.website': '웹사이트', 'resources.whitepaper': '백서', 'resources.faq': 'FAQ', 'resources.medium': 'Medium', 'resources.community': '커뮤니티', 'resources.compliance': '규정 준수', 'resources.complianceNote1': '노드 라이선스는 참여 권리이며 증권이나 투자가 아닙니다.', 'resources.complianceNote2': '기밀 커미션 요율이나 등급 기준을 공개하지 마세요.', 'resources.complianceNote3': '승인된 Operon 브랜드 자료만 사용하세요.', 'resources.complianceNote4': '관할 지역의 모든 관련 규정을 준수하세요.', 'resources.bridgeGuides': '브릿지 가이드', 'resources.bridgeArbitrum': 'Arbitrum으로 브릿지', 'resources.bridgeBsc': 'BNB Chain으로 브릿지',
  'sale.saleLive': '판매 중', 'sale.gasEstimate': 'Gas 예상', 'sale.tierSoldOut': '해당 등급 매진', 'sale.switchWallet': '전환', 'sale.liveUpdates': '실시간 업데이트', 'sale.updatesDelayed': '업데이트가 지연될 수 있습니다', 'sale.pendingTx': '대기 중인 거래 발견', 'sale.viewExplorer': '탐색기에서 보기', 'sale.each': '개당', 'sale.bridgeLink': '이더리움에서 브릿지 →', 'sale.txSlow': '거래가 예상보다 오래 걸리고 있습니다.', 'sale.discountLabel': '할인 ({discount}%)', 'sale.afterDiscount': '할인 후', 'sale.selfReferralWarning': '동일한 지갑에서 자신의 추천 코드를 사용하는 자기 추천은 추천 보상을 무효화합니다.', 'sale.selfReferralBlocked': '자신의 추천 코드를 사용할 수 없습니다.', 'sale.noActiveTier': '사용 가능한 판매 등급이 없습니다. 페이지를 새로고침해 주세요.', 'sale.pendingSync': '추천 코드를 체인에 동기화 중입니다. 잠시 후 다시 시도해 주세요.',
  'sale.walletDisconnected': '지갑 연결이 끊겼습니다. 다시 연결하고 거래 내역을 확인하세요.', 'sale.networkSlow': '네트워크가 느립니다 — 연결을 확인하세요', 'sale.codeAppliedToast': '추천 코드 적용됨 — {discount}% 할인 활성화!', 'sale.maxPerWallet': '지갑당 최대 10개', 'sale.approvalFailed': '승인 실패. 다시 시도하세요.', 'sale.purchaseFailed': '구매 실패. 다시 시도하세요.', 'sale.tierSoldOutN': '등급 {tier} 매진!', 'sale.tierNowActive': '등급 {tier} 판매 시작', 'sale.switchTo': '{chain}으로 전환', 'sale.needToken': '{token} 필요?', 'sale.approveToken': '{token} 승인', 'sale.purchaseNodes': '노드 {qty}개 구매', 'sale.insufficientToken': '{token} 잔액 부족', 'sale.priceTimesQty': '가격 × {qty}', 'sale.nodeInfo': '{qty} × ERC-721 NFT, {chain} · 노드당 기본 발행 63,000 $OPRN', 'sale.allPricesDiscount': '모든 가격 {discount}% 할인 포함',
  'auth.signingIn': '로그인 중... 지갑을 확인하세요', 'auth.signInFailed': '로그인 실패',
  'error.pageError': '문제가 발생했습니다', 'error.pageErrorDesc': '예기치 않은 오류가 발생했습니다. 다시 시도하거나 지원팀에 문의하세요.',
  'nav.overview': '개요', 'nav.staking': '스테이킹', 'nav.nodeOps': '노드 운영', 'nav.comingSoon': '곧 출시', 'nav.more': '더보기',
  'nodeCard.pricePaid': '지불 가격', 'nodeCard.dailyReward': '예상 일일 보상', 'nodeCard.purchased': '구매일', 'nodeCard.txHash': '거래 해시',
  'btn.dismiss': '닫기', 'btn.buyMoreNodes': '노드 더 구매 →', 'btn.tryAgain': '다시 시도',
  'sale.signInFirst': '먼저 로그인을 완료해 주세요.',
  'referrals.community.title': '커뮤니티 추천 프로그램', 'referrals.community.subtitle': '구매자는 {discount}% 할인을 받고, 귀하는 최대 5단계까지 모든 판매에 대해 커미션을 받습니다.', 'referrals.community.tableLevel': '레벨', 'referrals.community.tableYouEarn': '커미션', 'referrals.community.tableMax': '최대', 'referrals.community.disclaimer': '위의 추천 코드 또는 링크를 공유하세요. 자기 추천(동일한 지갑에서 자신의 코드 사용)은 추천 보상을 무효화합니다.',
  'feed.purchaseSingle': 'L{level} 추천인이 노드 1개 구매', 'feed.purchasePlural': 'L{level} 추천인이 노드 {count}개 구매', 'feed.signup': '새로운 L{level} 추천인이 네트워크에 가입', 'feed.tierPromotion': '{tier} 등급으로 승격', 'feed.milestone': '마일스톤 달성',
  'feed.justNow': '방금 전', 'feed.minAgo': '{n}분 전', 'feed.hrAgo': '{n}시간 전', 'feed.dayAgo': '{n}일 전',
  'sale.percentOff': '{discount}% 할인', 'sale.tierSoldLabel': '{tier} 등급 매진', 'sale.soldCountLabel': '판매됨', 'sale.codeInvalidBadge': '유효하지 않음', 'sale.priceTimesQtyLabel': '가격 × {qty}', 'sale.needTokenLabel': '{token} 필요?', 'sale.realtimeOffline': '실시간 업데이트 오프라인 — 새로고침하여 동기화하세요.', 'sale.refreshNow': '새로고침',
  'home.tierLabel': '{tier} 등급', 'home.investedLabel': '{amount} 투자',
  'sale.tierProgressLine': '{tier} 등급 · {remaining} / {supply} 잔여', 'sale.pendingTxSummary': '{chain}의 노드 {qty}개',
  'tierBar.tier': '{tier} 등급', 'tierBar.pricePerNode': '노드당 {price}', 'tierBar.soldOfSupply': '{sold} / {supply} 판매됨', 'tierBar.currentTier': '현재 등급',
  'code.copyCode': '코드 복사', 'code.share': '공유', 'code.copyLink': '추천 링크 복사', 'code.shareTitle': 'Operon 노드 판매', 'code.shareText': '제 추천 코드를 사용하세요: {code}',
};

// ─── Vietnamese (Tiếng Việt) ─────────────────────────────────────────────

const vi: Record<keyof typeof en, string> = {
  'nav.home': 'Bảng điều khiển', 'nav.nodes': 'Tác nhân AI', 'nav.sale': 'Bán Node', 'nav.referrals': 'Giới thiệu', 'nav.settings': 'Cài đặt', 'nav.docs': 'Tài liệu', 'nav.support': 'Hỗ trợ',
  'btn.connect_wallet': 'Kết nối ví', 'btn.disconnect': 'Ngắt kết nối', 'btn.buy_now': 'Mua ngay', 'btn.approve': 'Phê duyệt', 'btn.confirm': 'Xác nhận', 'btn.cancel': 'Hủy', 'btn.copy': 'Sao chép', 'btn.copied': 'Đã sao chép!', 'btn.view_all': 'Xem tất cả', 'btn.load_more': 'Tải thêm', 'btn.retry': 'Thử lại', 'btn.claim': 'Nhận', 'btn.delegate': 'Ủy quyền', 'btn.share': 'Chia sẻ',
  'page.home.title': 'Tổng quan', 'page.nodes.title': 'Tác nhân AI của tôi', 'page.sale.title': 'Bán Node', 'page.referrals.title': 'Mạng lưới giới thiệu', 'page.settings.title': 'Cài đặt',
  'stats.total_nodes': 'Tổng Node', 'stats.active_nodes': 'Node hoạt động', 'stats.total_earnings': 'Tổng thu nhập', 'stats.pending_commissions': 'Hoa hồng chờ', 'stats.network_size': 'Quy mô mạng', 'stats.partner_tier': 'Cấp đối tác', 'stats.nodes_available': 'Node khả dụng',
  'sale.stage.active': 'Hoạt động', 'sale.stage.paused': 'Tạm dừng', 'sale.stage.closed': 'Đã đóng', 'sale.current_price': 'Giá hiện tại', 'sale.next_price': 'Giá tiếp theo', 'sale.sold': 'Đã bán', 'sale.remaining': 'Còn lại', 'sale.enter_code': 'Nhập mã giới thiệu', 'sale.select_chain': 'Chọn chuỗi', 'sale.select_token': 'Chọn token thanh toán', 'sale.quantity': 'Số lượng', 'sale.total': 'Tổng', 'sale.discount_applied': 'Đã áp dụng giảm giá: {discount}%',
  'nodes.status.active': 'Hoạt động', 'nodes.status.delegated': 'Đã ủy quyền', 'nodes.status.locked': 'Đã khóa', 'nodes.purchased': 'Ngày mua', 'nodes.lifetime_rewards': 'Phần thưởng tích lũy', 'nodes.delegated_to': 'Ủy quyền cho', 'nodes.total_owned': 'Tổng sở hữu', 'nodes.total_rewards': 'Tổng phần thưởng',
  'referrals.code': 'Mã giới thiệu của bạn', 'referrals.total': 'Tổng giới thiệu', 'referrals.direct': 'Giới thiệu trực tiếp', 'referrals.indirect': 'Giới thiệu gián tiếp', 'referrals.commission_earned': 'Hoa hồng đã nhận', 'referrals.pending_commission': 'Hoa hồng chờ', 'referrals.network': 'Tổng quan mạng lưới', 'referrals.milestones': 'Cột mốc', 'referrals.activity': 'Hoạt động', 'referrals.payouts': 'Lịch sử thanh toán', 'referrals.level': 'Cấp {level}', 'referrals.members': 'Thành viên', 'referrals.sales': 'Doanh số', 'referrals.commission': 'Hoa hồng',
  'tier.affiliate': 'Liên kết', 'tier.partner': 'Đối tác', 'tier.senior': 'Đối tác cấp cao', 'tier.regional': 'Đối tác khu vực', 'tier.market': 'Đối tác thị trường', 'tier.founding': 'Đối tác sáng lập',
  'payout.pending': 'Chờ xử lý', 'payout.processing': 'Đang xử lý', 'payout.sent': 'Đã gửi', 'payout.confirmed': 'Đã xác nhận', 'payout.failed': 'Thất bại',
  'event.purchase': 'Mua Node', 'event.signup': 'Đăng ký mới', 'event.tier_promotion': 'Nâng cấp', 'event.milestone': 'Đạt cột mốc',
  'error.WRONG_CHAIN': 'Vui lòng chuyển sang {chain} để tiếp tục.', 'error.INSUFFICIENT_BALANCE': 'Số dư {token} không đủ. Bạn cần {required} nhưng chỉ có {available}.', 'error.SALE_CLOSED': 'Đợt bán node hiện đã đóng.', 'error.INVALID_CODE': 'Mã giới thiệu không hợp lệ. Vui lòng kiểm tra và thử lại.', 'error.ALREADY_REGISTERED': 'Ví này đã được đăng ký.', 'error.WALLET_NOT_CONNECTED': 'Vui lòng kết nối ví để tiếp tục.', 'error.SIGNATURE_REJECTED': 'Yêu cầu ký đã bị từ chối.', 'error.TX_FAILED': 'Giao dịch thất bại. Vui lòng thử lại.', 'error.TX_TIMEOUT': 'Giao dịch hết thời gian. Vui lòng kiểm tra ví.', 'error.RATE_LIMITED': 'Quá nhiều yêu cầu. Vui lòng đợi một chút.', 'error.UNAUTHORIZED': 'Phiên đã hết hạn. Vui lòng kết nối lại ví.', 'error.NOT_FOUND': 'Không tìm thấy tài nguyên yêu cầu.', 'error.SERVER_ERROR': 'Đã có lỗi xảy ra. Vui lòng thử lại sau.', 'error.NETWORK_ERROR': 'Lỗi mạng. Vui lòng kiểm tra kết nối.',
  'empty.nodes': 'Bạn chưa sở hữu node nào. Mua Tác nhân AI đầu tiên để bắt đầu.', 'empty.referrals': 'Chưa có giới thiệu. Chia sẻ mã giới thiệu để bắt đầu nhận hoa hồng.', 'empty.activity': 'Chưa có hoạt động nào.', 'empty.payouts': 'Chưa có thanh toán. Hoa hồng sẽ hiển thị khi được xử lý.',
  'misc.loading': 'Đang tải...', 'misc.powered_by': 'Được cung cấp bởi Operon Network', 'misc.language': 'Ngôn ngữ',
};

const pageKeysVi: Record<keyof typeof pageKeys, string> = {
  'home.welcome': 'Chào mừng đến với Operon', 'home.connectPrompt': 'Kết nối ví để truy cập bảng điều khiển', 'home.nodesOwned': 'Node sở hữu', 'home.estDailyEmission': 'Phát thải dự kiến/ngày', 'home.rewardsAtTge': 'Phần thưởng bắt đầu tại TGE', 'home.referralNetwork': 'Mạng giới thiệu', 'home.referrals': 'giới thiệu', 'home.genesisSale': 'Bán Node Khởi Nguyên', 'home.currentTier': 'Cấp hiện tại', 'home.active': 'Hoạt động', 'home.paused': 'Tạm dừng', 'home.closed': 'Đã đóng', 'home.price': 'Giá', 'home.remaining': 'còn lại', 'home.totalNodes': 'tổng node', 'home.buyNodes': 'Mua Node', 'home.yourReferralCode': 'Mã giới thiệu của bạn', 'home.shareToEarn': 'Chia sẻ để nhận hoa hồng', 'home.payoutWallet': 'Ví thanh toán',
  'sale.referralCode': 'Mã giới thiệu', 'sale.codeApplied': 'Đã áp dụng', 'sale.codeInvalid': 'Không hợp lệ', 'sale.tierStatus': 'Trạng thái cấp', 'sale.nodesRemaining': 'node còn lại', 'sale.purchaseDetails': 'Chi tiết mua hàng', 'sale.chain': 'Chuỗi', 'sale.switchChain': 'Chuyển sang {chain}', 'sale.payWith': 'Thanh toán bằng', 'sale.balance': 'Số dư', 'sale.pricePerNode': 'Giá mỗi node', 'sale.connectToBuy': 'Kết nối ví để mua', 'sale.insufficientBalance': 'Số dư không đủ', 'sale.approving': 'Đang phê duyệt...', 'sale.approve': 'Phê duyệt', 'sale.confirming': 'Đang xác nhận...', 'sale.purchase': 'Mua', 'sale.yourWallet': 'Ví của bạn', 'sale.purchaseComplete': 'Mua thành công!', 'sale.youNowOwn': 'Bạn hiện sở hữu {count} Operon Node (Cấp {tier})', 'sale.viewNodes': 'Xem Node của tôi', 'sale.buyMore': 'Mua thêm',
  'nodes.connectWallet': 'Kết nối ví để xem node', 'nodes.noNodes': 'Chưa có Node', 'nodes.noNodesDesc': 'Mua node đầu tiên để bắt đầu.', 'nodes.goToSale': 'Đi đến mua', 'nodes.estDailyEmission': 'Phát thải dự kiến/ngày', 'nodes.ownNodes': 'node sở hữu', 'nodes.referralPool': 'pool giới thiệu', 'nodes.owned': 'Sở hữu', 'nodes.invested': 'Đã đầu tư', 'nodes.chains': 'Chuỗi', 'nodes.inventory': 'Danh sách Node', 'nodes.disclaimer': 'Ước tính chỉ mang tính minh họa. Phần thưởng thực tế phụ thuộc vào hiệu suất mạng.',
  'nodes.pending.title': 'Đã xác nhận mua — đang xử lý ở backend', 'nodes.pending.body': 'Giao dịch {tx} của bạn đã được xác nhận on-chain. Backend thường hoàn tất việc gán quyền sở hữu trong 1–5 phút; thông báo này sẽ tự động biến mất khi node của bạn xuất hiện.', 'nodes.pending.overdue': 'Lâu hơn bình thường. Nếu vượt quá 15 phút, vui lòng liên hệ hỗ trợ kèm hash giao dịch.',
  'referrals.connectWallet': 'Kết nối ví để xem giới thiệu', 'referrals.elitePartner': 'Đối tác Tinh hoa', 'referrals.joined': 'Ngày tham gia', 'referrals.credited': 'Tín dụng', 'referrals.yourCode': 'Mã giới thiệu', 'referrals.eppShareLabel': 'Người mua được giảm 15%', 'referrals.shareLabel': 'Chia sẻ để nhận hoa hồng', 'referrals.tierProgress': 'Tiến trình cấp', 'referrals.commissionByLevel': 'Hoa hồng theo cấp', 'referrals.volume': 'doanh số', 'referrals.bonus': 'thưởng', 'referrals.achieved': 'Đã đạt', 'referrals.networkBreakdown': 'Chi tiết mạng', 'referrals.recentActivity': 'Hoạt động gần đây', 'referrals.noActivity': 'Chưa có hoạt động', 'referrals.payoutHistory': 'Lịch sử thanh toán', 'referrals.date': 'Ngày', 'referrals.amount': 'Số tiền', 'referrals.chain': 'Chuỗi', 'referrals.status': 'Trạng thái', 'referrals.noPayouts': 'Chưa có thanh toán. Hoa hồng được trả hai tuần một lần.', 'referrals.programmeReference': 'Tham khảo chương trình', 'referrals.commissionRates': 'Tỷ lệ hoa hồng', 'referrals.tier': 'Cấp', 'referrals.creditedWeights': 'Trọng số tín dụng',
  'resources.partnerMaterials': 'Tài liệu đối tác', 'resources.pitchManual': 'Sổ tay đào tạo', 'resources.brandAssets': 'Tài nguyên thương hiệu', 'resources.termsConditions': 'Điều khoản & Điều kiện', 'resources.download': 'Tải xuống', 'resources.usefulLinks': 'Liên kết hữu ích', 'resources.website': 'Trang web', 'resources.whitepaper': 'Whitepaper', 'resources.faq': 'FAQ', 'resources.medium': 'Medium', 'resources.community': 'Cộng đồng', 'resources.compliance': 'Tuân thủ', 'resources.complianceNote1': 'Giấy phép node là quyền tham gia, không phải chứng khoán hay đầu tư.', 'resources.complianceNote2': 'Không công bố tỷ lệ hoa hồng hoặc ngưỡng cấp bảo mật.', 'resources.complianceNote3': 'Chỉ sử dụng tài liệu thương hiệu Operon đã được phê duyệt.', 'resources.complianceNote4': 'Tuân thủ tất cả quy định hiện hành tại khu vực của bạn.', 'resources.bridgeGuides': 'Hướng dẫn Bridge', 'resources.bridgeArbitrum': 'Bridge sang Arbitrum', 'resources.bridgeBsc': 'Bridge sang BNB Chain',
  'sale.saleLive': 'Đang bán', 'sale.gasEstimate': 'Gas ước tính', 'sale.tierSoldOut': 'Cấp đã bán hết', 'sale.switchWallet': 'Chuyển', 'sale.liveUpdates': 'Cập nhật trực tiếp', 'sale.updatesDelayed': 'Cập nhật có thể bị trễ', 'sale.pendingTx': 'Phát hiện giao dịch đang chờ', 'sale.viewExplorer': 'Xem trên explorer', 'sale.each': 'mỗi cái', 'sale.bridgeLink': 'Bridge từ Ethereum →', 'sale.txSlow': 'Giao dịch đang mất nhiều thời gian hơn dự kiến.', 'sale.discountLabel': 'Giảm giá ({discount}%)', 'sale.afterDiscount': 'Sau giảm giá', 'sale.selfReferralWarning': 'Tự giới thiệu (sử dụng mã của chính bạn từ cùng một ví) sẽ làm mất hiệu lực phần thưởng giới thiệu.', 'sale.selfReferralBlocked': 'Bạn không thể sử dụng mã giới thiệu của chính mình.', 'sale.noActiveTier': 'Không có cấp nào đang bán. Vui lòng làm mới trang.', 'sale.pendingSync': 'Đang kích hoạt mã của bạn trên chuỗi — vui lòng thử lại sau vài giây.',
  'sale.walletDisconnected': 'Ví đã ngắt kết nối. Vui lòng kết nối lại và kiểm tra lịch sử giao dịch.', 'sale.networkSlow': 'Mạng chậm — vui lòng kiểm tra kết nối', 'sale.codeAppliedToast': 'Đã áp dụng mã giới thiệu — giảm {discount}%!', 'sale.maxPerWallet': 'Tối đa 10 mỗi ví', 'sale.approvalFailed': 'Phê duyệt thất bại. Vui lòng thử lại.', 'sale.purchaseFailed': 'Mua thất bại. Vui lòng thử lại.', 'sale.tierSoldOutN': 'Cấp {tier} đã bán hết!', 'sale.tierNowActive': 'Cấp {tier} hiện đang bán', 'sale.switchTo': 'Chuyển sang {chain}', 'sale.needToken': 'Cần {token}?', 'sale.approveToken': 'Phê duyệt {token}', 'sale.purchaseNodes': 'Mua {qty} Node', 'sale.insufficientToken': 'Số dư {token} không đủ', 'sale.priceTimesQty': 'Giá × {qty}', 'sale.nodeInfo': '{qty} × NFT ERC-721 trên {chain} · Phát thải cơ bản 63,000 $OPRN/node', 'sale.allPricesDiscount': 'Tất cả giá đã giảm {discount}%',
  'auth.signingIn': 'Đang đăng nhập... vui lòng kiểm tra ví', 'auth.signInFailed': 'Đăng nhập thất bại',
  'error.pageError': 'Đã xảy ra lỗi', 'error.pageErrorDesc': 'Đã xảy ra lỗi không mong muốn. Vui lòng thử lại hoặc liên hệ hỗ trợ.',
  'nav.overview': 'Tổng quan', 'nav.staking': 'Staking', 'nav.nodeOps': 'Vận hành Node', 'nav.comingSoon': 'Sắp ra mắt', 'nav.more': 'Thêm',
  'nodeCard.pricePaid': 'Giá đã trả', 'nodeCard.dailyReward': 'Phần thưởng/ngày (ước tính)', 'nodeCard.purchased': 'Ngày mua', 'nodeCard.txHash': 'Mã giao dịch',
  'btn.dismiss': 'Bỏ qua', 'btn.buyMoreNodes': 'Mua thêm Node →', 'btn.tryAgain': 'Thử lại',
  'sale.signInFirst': 'Vui lòng hoàn tất đăng nhập trước.',
  'referrals.community.title': 'Chương trình Giới thiệu Cộng đồng', 'referrals.community.subtitle': 'Người mua của bạn được giảm {discount}%. Bạn nhận hoa hồng cho mọi đơn hàng lên đến 5 cấp.', 'referrals.community.tableLevel': 'Cấp', 'referrals.community.tableYouEarn': 'Bạn nhận', 'referrals.community.tableMax': 'Tối đa', 'referrals.community.disclaimer': 'Chia sẻ mã hoặc liên kết giới thiệu ở trên. Tự giới thiệu (dùng mã của chính bạn từ cùng một ví) sẽ làm mất hiệu lực phần thưởng.',
  'feed.purchaseSingle': 'Giới thiệu L{level} đã mua 1 node', 'feed.purchasePlural': 'Giới thiệu L{level} đã mua {count} node', 'feed.signup': 'Một L{level} mới đã tham gia mạng lưới của bạn', 'feed.tierPromotion': 'Thăng lên Cấp {tier}', 'feed.milestone': 'Đạt cột mốc',
  'feed.justNow': 'vừa xong', 'feed.minAgo': '{n} phút trước', 'feed.hrAgo': '{n} giờ trước', 'feed.dayAgo': '{n} ngày trước',
  'sale.percentOff': 'giảm {discount}%', 'sale.tierSoldLabel': 'Cấp {tier} đã bán hết', 'sale.soldCountLabel': 'đã bán', 'sale.codeInvalidBadge': 'Không hợp lệ', 'sale.priceTimesQtyLabel': 'Giá × {qty}', 'sale.needTokenLabel': 'Cần {token}?', 'sale.realtimeOffline': 'Cập nhật trực tiếp ngoại tuyến — làm mới để đồng bộ.', 'sale.refreshNow': 'Làm mới',
  'home.tierLabel': 'Cấp {tier}', 'home.investedLabel': 'Đã đầu tư {amount}',
  'sale.tierProgressLine': 'Cấp {tier} · còn lại {remaining} / {supply}', 'sale.pendingTxSummary': '{qty} node trên {chain}',
  'tierBar.tier': 'Cấp {tier}', 'tierBar.pricePerNode': '{price} mỗi node', 'tierBar.soldOfSupply': 'đã bán {sold} / {supply}', 'tierBar.currentTier': 'Cấp hiện tại',
  'code.copyCode': 'Sao chép mã', 'code.share': 'Chia sẻ', 'code.copyLink': 'Sao chép liên kết giới thiệu', 'code.shareTitle': 'Operon Bán Node', 'code.shareText': 'Dùng mã giới thiệu của tôi: {code}',
};

// ─── Thai (ไทย) ──────────────────────────────────────────────────────────

const th: Record<keyof typeof en, string> = {
  'nav.home': 'แดชบอร์ด', 'nav.nodes': 'เอเจนต์ AI', 'nav.sale': 'ขายโหนด', 'nav.referrals': 'การแนะนำ', 'nav.settings': 'ตั้งค่า', 'nav.docs': 'เอกสาร', 'nav.support': 'ช่วยเหลือ',
  'btn.connect_wallet': 'เชื่อมต่อกระเป๋า', 'btn.disconnect': 'ยกเลิกการเชื่อมต่อ', 'btn.buy_now': 'ซื้อเลย', 'btn.approve': 'อนุมัติ', 'btn.confirm': 'ยืนยัน', 'btn.cancel': 'ยกเลิก', 'btn.copy': 'คัดลอก', 'btn.copied': 'คัดลอกแล้ว!', 'btn.view_all': 'ดูทั้งหมด', 'btn.load_more': 'โหลดเพิ่ม', 'btn.retry': 'ลองอีกครั้ง', 'btn.claim': 'เคลม', 'btn.delegate': 'มอบหมาย', 'btn.share': 'แชร์',
  'page.home.title': 'ภาพรวมแดชบอร์ด', 'page.nodes.title': 'เอเจนต์ AI ของฉัน', 'page.sale.title': 'ขายโหนด', 'page.referrals.title': 'เครือข่ายการแนะนำ', 'page.settings.title': 'ตั้งค่า',
  'stats.total_nodes': 'โหนดทั้งหมด', 'stats.active_nodes': 'โหนดที่ใช้งาน', 'stats.total_earnings': 'รายได้ทั้งหมด', 'stats.pending_commissions': 'ค่าคอมมิชชั่นรอดำเนินการ', 'stats.network_size': 'ขนาดเครือข่าย', 'stats.partner_tier': 'ระดับพาร์ทเนอร์', 'stats.nodes_available': 'โหนดที่พร้อมขาย',
  'sale.stage.active': 'กำลังขาย', 'sale.stage.paused': 'หยุดชั่วคราว', 'sale.stage.closed': 'ปิดการขาย', 'sale.current_price': 'ราคาปัจจุบัน', 'sale.next_price': 'ราคาถัดไป', 'sale.sold': 'ขายแล้ว', 'sale.remaining': 'เหลือ', 'sale.enter_code': 'ใส่รหัสแนะนำ', 'sale.select_chain': 'เลือกเชน', 'sale.select_token': 'เลือกโทเคนชำระเงิน', 'sale.quantity': 'จำนวน', 'sale.total': 'รวม', 'sale.discount_applied': 'ส่วนลดที่ใช้: {discount}%',
  'nodes.status.active': 'ใช้งาน', 'nodes.status.delegated': 'มอบหมายแล้ว', 'nodes.status.locked': 'ล็อค', 'nodes.purchased': 'วันที่ซื้อ', 'nodes.lifetime_rewards': 'รางวัลสะสม', 'nodes.delegated_to': 'มอบหมายให้', 'nodes.total_owned': 'ถือครองทั้งหมด', 'nodes.total_rewards': 'รางวัลทั้งหมด',
  'referrals.code': 'รหัสแนะนำของคุณ', 'referrals.total': 'การแนะนำทั้งหมด', 'referrals.direct': 'แนะนำโดยตรง', 'referrals.indirect': 'แนะนำทางอ้อม', 'referrals.commission_earned': 'คอมมิชชั่นที่ได้รับ', 'referrals.pending_commission': 'คอมมิชชั่นรอดำเนินการ', 'referrals.network': 'ภาพรวมเครือข่าย', 'referrals.milestones': 'เป้าหมาย', 'referrals.activity': 'กิจกรรม', 'referrals.payouts': 'ประวัติการจ่าย', 'referrals.level': 'ระดับ {level}', 'referrals.members': 'สมาชิก', 'referrals.sales': 'ยอดขาย', 'referrals.commission': 'คอมมิชชั่น',
  'tier.affiliate': 'แอฟฟิลิเอท', 'tier.partner': 'พาร์ทเนอร์', 'tier.senior': 'ซีเนียร์พาร์ทเนอร์', 'tier.regional': 'รีจิอนัลพาร์ทเนอร์', 'tier.market': 'มาร์เก็ตพาร์ทเนอร์', 'tier.founding': 'ฟาวน์ดิ้งพาร์ทเนอร์',
  'payout.pending': 'รอดำเนินการ', 'payout.processing': 'กำลังดำเนินการ', 'payout.sent': 'ส่งแล้ว', 'payout.confirmed': 'ยืนยันแล้ว', 'payout.failed': 'ล้มเหลว',
  'event.purchase': 'ซื้อโหนด', 'event.signup': 'สมัครใหม่', 'event.tier_promotion': 'เลื่อนระดับ', 'event.milestone': 'ถึงเป้าหมาย',
  'error.WRONG_CHAIN': 'กรุณาเปลี่ยนไปยัง {chain} เพื่อดำเนินการต่อ', 'error.INSUFFICIENT_BALANCE': 'ยอด {token} ไม่เพียงพอ ต้องการ {required} แต่มี {available}', 'error.SALE_CLOSED': 'การขายโหนดปิดแล้ว', 'error.INVALID_CODE': 'รหัสแนะนำไม่ถูกต้อง กรุณาตรวจสอบแล้วลองอีกครั้ง', 'error.ALREADY_REGISTERED': 'กระเป๋านี้ลงทะเบียนแล้ว', 'error.WALLET_NOT_CONNECTED': 'กรุณาเชื่อมต่อกระเป๋าเพื่อดำเนินการต่อ', 'error.SIGNATURE_REJECTED': 'คำขอลายเซ็นถูกปฏิเสธ', 'error.TX_FAILED': 'ธุรกรรมล้มเหลว กรุณาลองอีกครั้ง', 'error.TX_TIMEOUT': 'ธุรกรรมหมดเวลา กรุณาตรวจสอบกระเป๋า', 'error.RATE_LIMITED': 'คำขอมากเกินไป กรุณารอสักครู่', 'error.UNAUTHORIZED': 'เซสชันหมดอายุ กรุณาเชื่อมต่อกระเป๋าอีกครั้ง', 'error.NOT_FOUND': 'ไม่พบข้อมูลที่ต้องการ', 'error.SERVER_ERROR': 'เกิดข้อผิดพลาด กรุณาลองอีกครั้งภายหลัง', 'error.NETWORK_ERROR': 'เครือข่ายผิดพลาด กรุณาตรวจสอบการเชื่อมต่อ',
  'empty.nodes': 'คุณยังไม่มีโหนด ซื้อเอเจนต์ AI ตัวแรกเพื่อเริ่มต้น', 'empty.referrals': 'ยังไม่มีการแนะนำ แชร์รหัสแนะนำเพื่อเริ่มรับคอมมิชชั่น', 'empty.activity': 'ยังไม่มีกิจกรรม', 'empty.payouts': 'ยังไม่มีการจ่ายเงิน คอมมิชชั่นจะแสดงเมื่อดำเนินการแล้ว',
  'misc.loading': 'กำลังโหลด...', 'misc.powered_by': 'ขับเคลื่อนโดย Operon Network', 'misc.language': 'ภาษา',
};

const pageKeysTh: Record<keyof typeof pageKeys, string> = {
  'home.welcome': 'ยินดีต้อนรับสู่ Operon', 'home.connectPrompt': 'เชื่อมต่อกระเป๋าเพื่อเข้าถึงแดชบอร์ด', 'home.nodesOwned': 'โหนดที่ถือครอง', 'home.estDailyEmission': 'ประมาณการปล่อย/วัน', 'home.rewardsAtTge': 'รางวัลเริ่มต้นที่ TGE', 'home.referralNetwork': 'เครือข่ายการแนะนำ', 'home.referrals': 'การแนะนำ', 'home.genesisSale': 'Genesis Node Sale', 'home.currentTier': 'ระดับปัจจุบัน', 'home.active': 'กำลังขาย', 'home.paused': 'หยุดชั่วคราว', 'home.closed': 'ปิดแล้ว', 'home.price': 'ราคา', 'home.remaining': 'เหลือ', 'home.totalNodes': 'โหนดทั้งหมด', 'home.buyNodes': 'ซื้อโหนด', 'home.yourReferralCode': 'รหัสแนะนำของคุณ', 'home.shareToEarn': 'แชร์เพื่อรับคอมมิชชั่น', 'home.payoutWallet': 'กระเป๋ารับเงิน',
  'sale.referralCode': 'รหัสแนะนำ', 'sale.codeApplied': 'ใช้แล้ว', 'sale.codeInvalid': 'ไม่ถูกต้อง', 'sale.tierStatus': 'สถานะระดับ', 'sale.nodesRemaining': 'โหนดเหลือ', 'sale.purchaseDetails': 'รายละเอียดการซื้อ', 'sale.chain': 'เชน', 'sale.switchChain': 'เปลี่ยนไปยัง {chain}', 'sale.payWith': 'ชำระด้วย', 'sale.balance': 'ยอดคงเหลือ', 'sale.pricePerNode': 'ราคาต่อโหนด', 'sale.connectToBuy': 'เชื่อมต่อกระเป๋าเพื่อซื้อ', 'sale.insufficientBalance': 'ยอดไม่เพียงพอ', 'sale.approving': 'กำลังอนุมัติ...', 'sale.approve': 'อนุมัติ', 'sale.confirming': 'กำลังยืนยัน...', 'sale.purchase': 'ซื้อ', 'sale.yourWallet': 'กระเป๋าของคุณ', 'sale.purchaseComplete': 'ซื้อสำเร็จ!', 'sale.youNowOwn': 'คุณเป็นเจ้าของ {count} Operon Node (ระดับ {tier})', 'sale.viewNodes': 'ดูโหนดของฉัน', 'sale.buyMore': 'ซื้อเพิ่ม',
  'nodes.connectWallet': 'เชื่อมต่อกระเป๋าเพื่อดูโหนด', 'nodes.noNodes': 'ยังไม่มีโหนด', 'nodes.noNodesDesc': 'ซื้อโหนดแรกเพื่อเริ่มต้น', 'nodes.goToSale': 'ไปที่หน้าขาย', 'nodes.estDailyEmission': 'ประมาณการปล่อย/วัน', 'nodes.ownNodes': 'โหนดของตัวเอง', 'nodes.referralPool': 'พูลแนะนำ', 'nodes.owned': 'ถือครอง', 'nodes.invested': 'ลงทุนแล้ว', 'nodes.chains': 'เชน', 'nodes.inventory': 'รายการโหนด', 'nodes.disclaimer': 'ตัวเลขเป็นเพียงการประมาณ รางวัลจริงขึ้นอยู่กับประสิทธิภาพเครือข่าย',
  'nodes.pending.title': 'ยืนยันการซื้อแล้ว — กำลังประมวลผลที่ระบบหลังบ้าน', 'nodes.pending.body': 'ธุรกรรม {tx} ของคุณได้รับการยืนยันบนเชนแล้ว ระบบหลังบ้านมักจะดำเนินการให้เสร็จภายใน 1–5 นาที แจ้งเตือนนี้จะหายไปเองเมื่อโหนดของคุณปรากฏ', 'nodes.pending.overdue': 'ใช้เวลานานกว่าปกติ หากเกิน 15 นาทียังไม่เสร็จ กรุณาติดต่อฝ่ายช่วยเหลือพร้อมแฮชธุรกรรม',
  'referrals.connectWallet': 'เชื่อมต่อกระเป๋าเพื่อดูการแนะนำ', 'referrals.elitePartner': 'พาร์ทเนอร์ชั้นนำ', 'referrals.joined': 'วันที่เข้าร่วม', 'referrals.credited': 'เครดิต', 'referrals.yourCode': 'รหัสแนะนำ', 'referrals.eppShareLabel': 'ผู้ซื้อได้รับส่วนลด 15%', 'referrals.shareLabel': 'แชร์เพื่อรับคอมมิชชั่น', 'referrals.tierProgress': 'ความก้าวหน้าระดับ', 'referrals.commissionByLevel': 'คอมมิชชั่นตามระดับ', 'referrals.volume': 'ยอดขาย', 'referrals.bonus': 'โบนัส', 'referrals.achieved': 'สำเร็จ', 'referrals.networkBreakdown': 'รายละเอียดเครือข่าย', 'referrals.recentActivity': 'กิจกรรมล่าสุด', 'referrals.noActivity': 'ยังไม่มีกิจกรรม', 'referrals.payoutHistory': 'ประวัติการจ่าย', 'referrals.date': 'วันที่', 'referrals.amount': 'จำนวน', 'referrals.chain': 'เชน', 'referrals.status': 'สถานะ', 'referrals.noPayouts': 'ยังไม่มีการจ่าย คอมมิชชั่นจ่ายทุกสองสัปดาห์', 'referrals.programmeReference': 'ข้อมูลอ้างอิงโปรแกรม', 'referrals.commissionRates': 'อัตราคอมมิชชั่น', 'referrals.tier': 'ระดับ', 'referrals.creditedWeights': 'น้ำหนักเครดิต',
  'resources.partnerMaterials': 'เอกสารพาร์ทเนอร์', 'resources.pitchManual': 'คู่มือการนำเสนอ', 'resources.brandAssets': 'สื่อแบรนด์', 'resources.termsConditions': 'ข้อกำหนดและเงื่อนไข', 'resources.download': 'ดาวน์โหลด', 'resources.usefulLinks': 'ลิงก์ที่เป็นประโยชน์', 'resources.website': 'เว็บไซต์', 'resources.whitepaper': 'Whitepaper', 'resources.faq': 'FAQ', 'resources.medium': 'Medium', 'resources.community': 'ชุมชน', 'resources.compliance': 'การปฏิบัติตามกฎ', 'resources.complianceNote1': 'ใบอนุญาตโหนดเป็นสิทธิ์ในการเข้าร่วม ไม่ใช่หลักทรัพย์หรือการลงทุน', 'resources.complianceNote2': 'ห้ามเผยแพร่อัตราคอมมิชชั่นหรือเกณฑ์ระดับที่เป็นความลับ', 'resources.complianceNote3': 'ใช้เฉพาะสื่อแบรนด์ Operon ที่ได้รับอนุมัติ', 'resources.complianceNote4': 'ปฏิบัติตามกฎระเบียบที่บังคับใช้ทั้งหมดในเขตอำนาจศาลของคุณ', 'resources.bridgeGuides': 'คู่มือ Bridge', 'resources.bridgeArbitrum': 'Bridge ไป Arbitrum', 'resources.bridgeBsc': 'Bridge ไป BNB Chain',
  'sale.saleLive': 'กำลังขาย', 'sale.gasEstimate': 'Gas โดยประมาณ', 'sale.tierSoldOut': 'ระดับนี้ขายหมดแล้ว', 'sale.switchWallet': 'สลับ', 'sale.liveUpdates': 'อัปเดตแบบเรียลไทม์', 'sale.updatesDelayed': 'การอัปเดตอาจล่าช้า', 'sale.pendingTx': 'พบธุรกรรมที่รอดำเนินการ', 'sale.viewExplorer': 'ดูบน explorer', 'sale.each': 'ต่อชิ้น', 'sale.bridgeLink': 'Bridge จาก Ethereum →', 'sale.txSlow': 'ธุรกรรมใช้เวลานานกว่าที่คาดไว้', 'sale.discountLabel': 'ส่วนลด ({discount}%)', 'sale.afterDiscount': 'หลังส่วนลด', 'sale.selfReferralWarning': 'การแนะนำตัวเอง (ใช้รหัสของคุณเองจากกระเป๋าเงินเดียวกัน) จะทำให้รางวัลการแนะนำเป็นโมฆะ', 'sale.selfReferralBlocked': 'คุณไม่สามารถใช้รหัสแนะนำของตัวเองได้', 'sale.noActiveTier': 'ไม่มีระดับที่กำลังขาย โปรดรีเฟรชหน้า', 'sale.pendingSync': 'กำลังเปิดใช้งานรหัสของคุณบนเชน โปรดลองอีกครั้งในอีกสักครู่',
  'sale.walletDisconnected': 'การเชื่อมต่อกระเป๋าถูกตัดแล้ว กรุณาเชื่อมต่อใหม่และตรวจสอบประวัติธุรกรรม', 'sale.networkSlow': 'เครือข่ายช้า — กรุณาตรวจสอบการเชื่อมต่อของคุณ', 'sale.codeAppliedToast': 'ใช้รหัสแนะนำแล้ว — ได้ส่วนลด {discount}% แล้ว!', 'sale.maxPerWallet': 'สูงสุด 10 ต่อกระเป๋า', 'sale.approvalFailed': 'การอนุมัติล้มเหลว กรุณาลองอีกครั้ง', 'sale.purchaseFailed': 'การซื้อล้มเหลว กรุณาลองอีกครั้ง', 'sale.tierSoldOutN': 'ระดับ {tier} ขายหมดแล้ว!', 'sale.tierNowActive': 'ระดับ {tier} กำลังขาย', 'sale.switchTo': 'เปลี่ยนไปยัง {chain}', 'sale.needToken': 'ต้องการ {token}?', 'sale.approveToken': 'อนุมัติ {token}', 'sale.purchaseNodes': 'ซื้อโหนด {qty} ชิ้น', 'sale.insufficientToken': 'ยอด {token} ไม่เพียงพอ', 'sale.priceTimesQty': 'ราคา × {qty}', 'sale.nodeInfo': '{qty} × ERC-721 NFT บน {chain} · การปล่อยพื้นฐาน 63,000 $OPRN ต่อโหนด', 'sale.allPricesDiscount': 'ราคาทั้งหมดรวมส่วนลด {discount}%',
  'auth.signingIn': 'กำลังเข้าสู่ระบบ... กรุณาตรวจสอบกระเป๋า', 'auth.signInFailed': 'เข้าสู่ระบบล้มเหลว',
  'error.pageError': 'เกิดข้อผิดพลาด', 'error.pageErrorDesc': 'เกิดข้อผิดพลาดที่ไม่คาดคิด กรุณาลองอีกครั้งหรือติดต่อฝ่ายสนับสนุน',
  'nav.overview': 'ภาพรวม', 'nav.staking': 'สเตกกิ้ง', 'nav.nodeOps': 'จัดการโหนด', 'nav.comingSoon': 'เร็วๆ นี้', 'nav.more': 'เพิ่มเติม',
  'nodeCard.pricePaid': 'ราคาที่จ่าย', 'nodeCard.dailyReward': 'รางวัลรายวัน (ประมาณ)', 'nodeCard.purchased': 'วันที่ซื้อ', 'nodeCard.txHash': 'แฮชธุรกรรม',
  'btn.dismiss': 'ปิด', 'btn.buyMoreNodes': 'ซื้อโหนดเพิ่ม →', 'btn.tryAgain': 'ลองอีกครั้ง',
  'sale.signInFirst': 'โปรดเข้าสู่ระบบให้เสร็จก่อน',
  'referrals.community.title': 'โปรแกรมแนะนำชุมชน', 'referrals.community.subtitle': 'ผู้ซื้อของคุณได้รับส่วนลด {discount}% คุณรับค่าคอมมิชชั่นจากทุกการขายสูงสุด 5 ระดับ', 'referrals.community.tableLevel': 'ระดับ', 'referrals.community.tableYouEarn': 'คุณได้', 'referrals.community.tableMax': 'สูงสุด', 'referrals.community.disclaimer': 'แชร์รหัสหรือลิงก์แนะนำด้านบน การแนะนำตัวเอง (ใช้รหัสของคุณเองจากกระเป๋าเดียวกัน) จะทำให้รางวัลการแนะนำเป็นโมฆะ',
  'feed.purchaseSingle': 'ผู้แนะนำ L{level} ซื้อ 1 โหนด', 'feed.purchasePlural': 'ผู้แนะนำ L{level} ซื้อ {count} โหนด', 'feed.signup': 'มีผู้แนะนำ L{level} ใหม่เข้าร่วมเครือข่ายของคุณ', 'feed.tierPromotion': 'เลื่อนเป็นระดับ {tier}', 'feed.milestone': 'ถึงเป้าหมาย',
  'feed.justNow': 'เมื่อสักครู่', 'feed.minAgo': '{n} นาทีที่แล้ว', 'feed.hrAgo': '{n} ชั่วโมงที่แล้ว', 'feed.dayAgo': '{n} วันที่แล้ว',
  'sale.percentOff': 'ลด {discount}%', 'sale.tierSoldLabel': 'ระดับ {tier} ขายหมดแล้ว', 'sale.soldCountLabel': 'ขายแล้ว', 'sale.codeInvalidBadge': 'ไม่ถูกต้อง', 'sale.priceTimesQtyLabel': 'ราคา × {qty}', 'sale.needTokenLabel': 'ต้องการ {token}?', 'sale.realtimeOffline': 'การอัปเดตแบบเรียลไทม์ออฟไลน์ — รีเฟรชเพื่อซิงค์', 'sale.refreshNow': 'รีเฟรช',
  'home.tierLabel': 'ระดับ {tier}', 'home.investedLabel': 'ลงทุนแล้ว {amount}',
  'sale.tierProgressLine': 'ระดับ {tier} · เหลือ {remaining} / {supply}', 'sale.pendingTxSummary': '{qty} โหนดบน {chain}',
  'tierBar.tier': 'ระดับ {tier}', 'tierBar.pricePerNode': '{price} ต่อโหนด', 'tierBar.soldOfSupply': 'ขายแล้ว {sold} / {supply}', 'tierBar.currentTier': 'ระดับปัจจุบัน',
  'code.copyCode': 'คัดลอกรหัส', 'code.share': 'แชร์', 'code.copyLink': 'คัดลอกลิงก์แนะนำ', 'code.shareTitle': 'Operon ขายโหนด', 'code.shareText': 'ใช้รหัสแนะนำของฉัน: {code}',
};

// ─── Export ──────────────────────────────────────────────────────────────

export type TranslationKey = keyof typeof en;
export type PageKey = keyof typeof pageKeys;
export type AllKeys = TranslationKey | PageKey;

// Compile-time parity check: each non-EN language pack must declare every key
// that EN declares. CLAUDE.md Rule 6 + REVIEW_ADDENDUM C-P4 claim TypeScript
// catches this; previously the dicts were typed Record<string, string> so the
// claim was vacuous. The two assertions below force the compiler to do its job.
type _AssertTcParity = {
  base: AssertEqual<keyof typeof tc, TranslationKey>;
  page: AssertEqual<keyof typeof pageKeysTc, PageKey>;
};
type _AssertScParity = {
  base: AssertEqual<keyof typeof sc, TranslationKey>;
  page: AssertEqual<keyof typeof pageKeysSc, PageKey>;
};
type _AssertKoParity = {
  base: AssertEqual<keyof typeof ko, TranslationKey>;
  page: AssertEqual<keyof typeof pageKeysKo, PageKey>;
};
type _AssertViParity = {
  base: AssertEqual<keyof typeof vi, TranslationKey>;
  page: AssertEqual<keyof typeof pageKeysVi, PageKey>;
};
type _AssertThParity = {
  base: AssertEqual<keyof typeof th, TranslationKey>;
  page: AssertEqual<keyof typeof pageKeysTh, PageKey>;
};

// Type-level equality helper. If the two unions don't match exactly, this
// resolves to `never` and the surrounding type errors. Both assertions in this
// file feed into the build, so a missing or stray key in any non-EN pack is a
// build-time error rather than a silent runtime fallthrough to EN.
type AssertEqual<A, B> =
  [A] extends [B] ? ([B] extends [A] ? true : never) : never;

export const translations: Record<Language, Record<AllKeys, string>> = {
  en: { ...en, ...pageKeys },
  tc: { ...tc, ...pageKeysTc },
  sc: { ...sc, ...pageKeysSc },
  ko: { ...ko, ...pageKeysKo },
  vi: { ...vi, ...pageKeysVi },
  th: { ...th, ...pageKeysTh },
};
